<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// Imported from v3
	'user' => 'Пользователь',
	'tasknodue' => 'не доступно',
	'dupdatedtickets' => 'Билеты на обновление с момента последнего входа:',
	'ddocs' => 'Документация Продукта',

	// Staff Dashboard
	'overview' => 'Краткий обзор (Нерешенные)',
	'dashboard' => 'Приборная панель',
	'quickinsert' => 'Быстрая вставка',
	'ticket' => 'Билет',
	'contact' => 'Контакт',
	'event' => 'Событие',
	'task' => 'Задание',
	'news' => 'Новость',
	'file' => 'Файл',
	'article' => 'Статья',
	'day' => 'День',
	'week' => 'Неделя',
	'workweek' => 'Рабочая неделя',
	'month' => 'Месяц',
	'dashtoday' => 'Сегодня',
	'overduetickets' => 'Просроченные билеты',
	'ticketsduetoday' => 'Билеты за сегодня',
	'dashtoday2' => 'Сегодня',
	'dashnews' => 'Новости (%s)',
	'dashnewstitle' => 'Последние новости',
	'undated' => 'Недатированный',
	'dashduetasks' => 'Просроченные задачи / задачи без даты',
	'tasksduetoday' => 'Задачи за сегодня',
	'nwpostedby' => 'Добавил',
	'nwpostedon' => 'Количество публикаций на',
	'nwread' => 'Читать',
	'statistics' => 'Статистика',
	'dnewtickets' => 'Новые билеты с момента последнего входа:',
	'dnewchats' => 'Новые чаты с момента последнего входа:',
	'twtoday' => 'Сегодня',
	'tabrecentchats' => 'Новые чаты',
	'tabrecentmessages' => 'Новые сообщения / Обзоры',
	'lcchatid' => 'ID чата',
	'lcfullname' => 'Полное имя',
	'lcstaff' => 'Персонал',
	'lcdepartment' => 'Подразделение',
	'lcmessageid' => 'ID сообщения',
	'lcsubject' => 'Тема',
	'dashmytickets' => 'Мои билеты',
	'dashunassigned' => 'Нераспределенные',
	'dashcomments' => 'Комментарии',
	'taboverduetickets' => 'Просроченные билеты',
	'dashticketid' => 'ID билета',
	'dashsubject' => 'Тема',
	'dashowner' => 'Владелец',
	'dashdepartment' => 'Подразделение',
	'dashstatus' => 'Статус',
	'dashdepartmentprogress' => 'Подразделение',
	'dashstatusprogress' => 'Статус',
	'dashtypeprogress' => 'Разновидность',
	'dashownerprogress' => 'Владелец',
	'dashpriorityprogress' => 'Приоритет',
	'unresolveddash' => 'Неразрешенный',
	'unassigneddash' => 'Нераспределенные',

	// Admin Dashboard
	'licunlimited' => '- Неограниченный -',
	'licdomains' => 'Домен(s)',
	'licstaff' => 'Лицензированый Персонал',
	'licexpires' => 'Истекает',
	'licowner' => 'Владелец',
	'licuniqueid' => 'Уникальный идентификатор',
	'licversion' => 'Версия',
	'licorganization' => 'Организация',
	'logfailure' => 'ОТКАЗ',
	'plogfrom' => 'Из:',
	'plogto' => 'Для:',
	'plogsize' => 'Размер:',
	'plognosubject' => 'Без темы',
	'showingmsg' => ' (Показано %d из %d)',
	'titletemplaterevert' => 'Шаблон: Для обновления требуется  возвращение',
	'msgtemplaterevert' => '"%d" шаблон(s) требует восстановления в связи с недавним обновлением:',
	'titlelanguagerevert' => 'Язык: Для обновления требуется  возвращение',
	'msglanguagerevert' => '"%d" фраза языка(s) требует восстановления в связи с недавним обновлением:',
	'licensedetails' => 'Детали Лицензии',
	'latestkayakonews' => 'Последние Новости Kayako',
	'tabwelcome' => 'Добро пожаловать',
	'tabrecentactivity' => 'Недавняя Деятельность',
	'tabalerts' => 'Оповещения',
	'tabloginfailures' => 'Отказы Логина',
	'taberrorlog' => 'Журнал Регистрации ошибок',
	'tabparserlog' => 'Журнал Регистрации Анализатора',
	'dashipaddress' => 'Адрес IP: ',
	'dashforwardedipaddress' => 'Дополнительный Адрес IP: ',
	'dashuseragent' => 'Пользователь агента: ',
	'dashinterface' => 'Интерфейс: ',
	'titleloginfailuredetectedone' => 'Обнаруженный Отказ Логина',
	'msgloginfailuredetectedone' => SWIFT_PRODUCT . ' обнаружил Отказ Логина. Вы можете проверить полный Лог в разделе > Логин регистрации.',
	'titleloginfailuredetected' => '%d Обнаруженные Отказы Логина',
	'msgloginfailuredetected' => SWIFT_PRODUCT . ' обнаружил %d Отказы Логина. Вы можете проверить полный Лог в разделе > Логин регистрации.',
	'titleparserlogfailuredetected' => '%d Отказ Лога Анализатора(s) Обнаружено',
	'msgparserlogfailuredetected' => SWIFT_PRODUCT . ' обнаружил %d Отказ Лога Анализатора(s). Вы можете проверить полный Лог в разделе > Логин регистрации.',
	'titleerrorsdetected' => '%d Ошибку(s) Зарегистрировано',
	'msgerrorsdetected' => SWIFT_PRODUCT . ' Зарегистрировано %d Ошибку(s). Для того, чтобы устранить эти ошибки, мы рекомендуем вам обратиться в службу поддержки Кэяко  с полным описанием ошибки.',
	'dashusername' => 'Имя пользователя:',
	'dashemail' => 'Электронная почта:',
	'dashlastlogin' => 'Последний Логин:',
	'dashversion' => 'версия',
	'dashproduct' => 'товар',
	'dashdashboard' => 'приборная панель',
	'dproduct' => 'Продукт:',
	'dversion' => 'Версия: ',
	'dbuildtype' => 'Тип создания: ',
	'dbuilddate' => 'Дата создания: ',
	'kayako' => 'Кэяко',
	'dhomepage' => 'Домашняя страница',
	'dsupportdesk' => 'Служба поддержки',
	'dmembersarea' => 'Вход для клиентов',
	'dforums' => 'Форум',
	'dtemplategroups' => 'Шаблон группы:',
	'dtemplates' => 'Шаблоны:',
	'dlanguages' => 'Языки:',
	'dphrases' => 'Фразы:',
	'dcustomfields' => 'Настраиваемые поля:',
	'dtasks' => 'Запланированные задания:',
	'dtables' => 'Таблицы базы данных:',
	'ddatabasesize' => 'Размер базы данных:',
	'dstaff' => 'Персонал пользователя:',
	'ddepartments' => 'Отделы:',
	'drecentactivity' => 'Недавняя Деятельность',
	'drecentactivitynone' => 'Нет доступной информации о недавней деятельности',
	'accreated' => 'СОЗДАНА',
	'acupdated' => 'ОБНОВЛЕНО',
	'acdeleted' => 'УДАЛЕННЫЙ',
	'acother' => 'ДРУГИЕ',
);
?>