<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN V4 LOCALES =======
	'languageisenabled' => 'Разрешен?',
	'desc_languageisenabled' => 'Если разрешен, язык будет виден в центре поддержки и в опциях профиля пользователя.',
	'titlemissingphrases' => 'Найдены Отсутствующие Фразы',
	'msgmissingphrases' => SWIFT_PRODUCT . ' Обнаружены "%d" пропавшие фразы, рекомендуется обновить выбранный язык и вставить все недостающие фразы.',
	'tabimport' => 'импортировать',
	'tabexport' => 'экспортировать',
	'languagemen' => 'Язык',
	'export' => 'Экспортировать',
	'import' => 'Импортировать',
	'squicksearch' => 'Быстрый Поиск',
	'titleupdatedlangphrases' => 'Обновленные Фразы Языка',
	'msgupdatedlangphrases' => 'Успешно обновлены фразы для "%s" Языка',
	'titlevcfailed' => 'Проверка версии не удалась',
	'msgvcfailed' => 'Пересланный пакет языка был создан, пользуясь старшей версией'.SWIFT_PRODUCT .'. Вы можете вызвать импортное/слияние, урегулировав настройки в "Ignore Version" опцией "Yes".',
	'titlelangimpfailed' => 'Импортное/Слияние Терпело неудачу',
	'msglangimpfailed' => SWIFT_PRODUCT.' был не в состоянии импортировать/слить ваш файл языка. Проверьте свой файл XML на любые неподходящие признаки или данные.',
	'tabsearch' => 'Поиск',
	'tabgeneral' => 'Общий',
	'flagicon' => 'Икона Флага',
	'desc_flagicon' => 'Укажите Изображение Иконки флага URL. По умолчанию иконки пакета флага хранятся в темах / глобальные / флаги каталога. Вы можете использовать следующие переменные:<br><b>{$themepath}</b> - URL указатель для каталога темы<br> - Пример: {$themepath}us.gif',
	'wineditlanguage' => 'Изменить Язык: %s',
	'phrases' => 'Фразы',
	'tabphrases' => 'Фразы',
	'insertphrase' => 'Вставить Фразу',
	'desc_insertphrase' => '',
	'tabgeneral' => 'Общий',
	'phraselanguage' => 'Фраза языка',
	'desc_phraselanguage' => 'Укажите язык, на котором должна быть добавлена фраза',
	'titlemergelang' => 'Успешное Слияние Языка',
	'msgmergelang' => 'Успешно поглотил XML с языком "%s".',
	'titleimportlang' => 'Язык импортирован успешно',
	'msgimportlang' => 'Успешно импортировал язык xml, новые детали языка есть ниже:',
	'titlephraseinsert' => 'Вставленная Фраза Языка "%s"',
	'msgphraseinsert' => 'Успешно вставлена фраза "%s" в таблице языка.<br /><b>Язык: </b>%s<br /><b>Код фразы:</b> %s<br /><b>Раздел фразы:</b> %s<br /><b>Соотношение фразы:</b> %s',
	'titlephrasedel' => 'Удалена Фраза Языка',
	'msgphrasedel' => 'Успешно удалена фраза языка "%s" из таблицы языка',
	'titleinsertlang' => 'Язык Добавлен: <b>%s</b>',
	'msginsertlang' => 'Успешно добавлен язык <b>"%s"</b>, новые детали языка есть ниже:',
	'titleupdatelang' => 'Язык Обновлен: <b>%s</b>',
	'msgupdatelang' => 'Успешное обновление языка <b>"%s"</b>, детали обновленногоязыка есть ниже:',
	'titledellang' => 'Удален "%d" Язык(s)',
	'msgdellang' => 'Успешно удалены следующие языки из базы данных.<br>',
	'compare' => 'Сравнить',
	'restorelanguage' => 'Восстановление языка',
	'restoreconfirm' => 'Вы уверены, что вы хотите восстановить фразы для данного языка по умолчанию? \ п Восстановление стирает все переводы фраз на данном языке.',
	'titlerestorephrase' => 'Восстановимые Фразы Языка',
	'msgrestorephrase' => 'Успешное восстановление всех фраз на языке "%s" к состоянию по умолчанию.',
	'diagnostics' => 'Диагностика',
	'tabmissingphrases' => 'Отсутствующие Фразы',
	'diagnosticslang1' => 'Язык',
	'desc_diagnosticslang1' => 'Пожалуйста, выберите основной язык для сравнения.',
	'diagnosticslang2' => 'Сравнить с',
	'desc_diagnosticslang2' => 'Пожалуйста, выберите язык для сравнения отсутствующих фраз с. '.SWIFT_PRODUCT.' выведет список всех фраз, которые отсутствуют в основной язык и существуют в языке, с которым вы сравниваете.',
	'restorephrases' => 'Восстановление Фразы',
	'desc_restorephrases' => '',
	'tabrestorephrases' => 'Восстановление Фразы',
	'lookup' => 'Поиск',
	'modified' => 'Изменение',
	'upgraderevert' => 'Обновление Требует Вернуться',
	'notmodified' => 'Не Модифицировано',
	'titlenooptsel' => 'Неверно выбран тип Фразы',
	'msgnooptsel' => 'Вы должны выбрать по крайней мере один тип фразы, чтобы отфильтровать результаты.',
	'restore' => 'Восстановление',
	'titleunabledelmasterlang' => 'Не удается удалить',
	'msgunabledelmasterlang' => SWIFT_PRODUCT.' не в состоянии удалить мастер языка. Вы можете переключать язык, используемый для группы по умолчанию, но удаление мастера языка не допускается.',
	'phrasesection' => 'Раздел',
	'desc_phrasesection' => 'Введите языка раздел в соответствии с которым нужно сохранить новую фразу. Для получения дополнительной информации о пакетных разделах языка, см. <a target="_blank" href="https://support.kayako.com/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=251">Статья Базы Знаний</a>. Рекомендуется, чтобы это было сведено к глобальному разделу "по умолчанию", если вы хотите настроить определенный шаблон.',
	'phrasestatus' => 'Статус Фразы',
	'restorelanguage2' => 'Восстановите Фразы Языка: %s',
	'restorelanguage3' => 'Язык: %s',
	'titlerestorephrases' => 'Восстановлены "%d" Фразы',
	'msgrestorephrases' => 'Успешно восстановлены следующие фразы языка:',
	'phrasemissing' => '-- ОТСУТСТВУЕТ --',
	// ======= END V4 LOCALES =======

	// ======= BEGIN v3 IMPORT =======
	'section' => 'Section',
	// ======= END v3 IMPORT =======

	'languages' => 'Язык',
	'languagedetails' => 'Детали Языка',
	'desc_languages' => '',
	'languagelist' => 'Список Языков',
	'languagetitle' => 'Название Языка',
	'desc_languagetitle' => 'Введите название для языка. <i>Пример: "English (U.S.)"</i>',
	'authorname' => 'Автор',
	'desc_authorname' => 'Введите имя Автора.',
	'isdefault' => 'По умолчанию',
	'desc_isdefault' => 'Если разрешается, этот язык будет установлен как язык по умолчанию',
	'textdirection' => 'Ориентация Текста',
	'desc_textdirection' => 'Выберите ориентацию текста на языке.',
	'isocode' => 'ISO Код',
	'desc_isocode' => 'Введите ISO код для языка. <a href="http://www.iso.org/iso/english_country_names_and_code_elements" target="_blank">Нажмите здесь</a> для списка ISO кодов.<br><br><b>Примеры:</b><br><i>en-us:</i> English (U.S.)<br><i>ru:</i> Russian<br><i>fr:</i> French',
	'languagecharset' => 'Набор символов',
	'desc_languagecharset' => 'Введите HTML кодировку по умолчанию. Используйте <i>UTF-8</i> для языков, которые требуют Unicode.',
	'rtl' => 'Справа налево',
	'ltr' => 'Слева направо',
	'displayorder' => 'Порядок отображения',
	'desc_displayorder' => 'Если есть многоразовые языки в пределах области, они сортируются с использованием порядка отображения (по возрастанию) указанном здесь.',
	'insertlanguage' => 'Добавить Язык',
	'phrases' => 'Фразы',
	'invalidlanguageid' => 'Неверный ID Языка!',
	'languagedeleteconfirmation' => 'Язык "%s" успешно удален',
	'languageinsertconfirmation' => 'Язык "%s" успешно добавлен',
	'languageupdateconfirmation' => 'Язык "%s" успешно обновлен',
	'importexport' => 'Импортировать/Экспортировать',
	'exportlanguage' => 'Экспортировать Язык',
	'explanguage' => 'Язык для экспортирования',
	'desc_explanguage' => 'Выберите язык, который Вы желаете экспортировать.',
	'exportxml' => 'Экспортировать',
	'importlanguage' => 'Импортировать ЯЗык',
	'importxml' => 'Импортировать',
	'languagefile' => 'XML Файл для импортирования',
	'desc_languagefile' => 'Рассматрите пакет языка, который вы желаете импортировать.',
	'mergewith' => 'Метод импортировать',
	'desc_mergewith' => '<i>Создать Новый Язык:</i> Создать совершенно новый языковой пакет на основе файла XML.<br><br><i>Выбрать Язык:</i> Слияние фраз найти в файле XML с указанного языка.',
	'ignoreversion' => 'Проверка Версии Bypass',
	'desc_ignoreversion' => 'Выберите, хотите вы или нет '. SWIFT_PRODUCT .' игнорировать информацию о версии в файле языкового пакета.  Настоятельно рекомендуется, что вы не импортировали языковых файлов, которые были предназначены для предыдущей версии '. SWIFT_PRODUCT .'.',
	'createnewlanguage' => '-- Создать новый язык --',
	'languageimportconfirmation' => 'Язык "%s" успешно импортирован',
	'managephrases' => 'Управление Фразы',
	'code' => 'Идентификатор',
	'value' => 'Текст',
	'phraseupdateconfirm' => 'Фразы успешно обновлены',
	'managephrases' => 'Управление Фразы',
	'searchphrases' => 'Поиск фраз',
	'languagesearching' => 'Поиск в ходе...',
	'search' => 'Поиск',
	'codetext' => 'Идентификатор и текст',
	'query' => 'Поиск запросов',
	'desc_query' => 'Введите поисковый запрос.',
	'searchtype' => 'Тип поиска',
	'desc_searchtype' => '<i>Идентификатор и текст:</i> Поиск в фразе текст и идентификатор.<br><br><i>Идентификатор:</i> Искать идентификатор только в фразе.',
	'searchlanguage' => 'Поиск Языка',
	'desc_searchlanguage' => 'Выберите язык для поиска в.',
	'versioncheckfailed' => 'ОШИБКА: Проверка версии не удалось. Языковой пакет был создан для старых версий'. SWIFT_PRODUCT,
	'addphrase' => 'Добавить Фразу',
	'changelanguage' => 'Переход языка',
	'desc_phrasecode' => 'Пожалуйста, введите уникальный идентификатор для новой фразы. <i>Example: "mynewphrase"</i>.',
	'desc_phrasevalue' => 'Введите содержание фразы. Вы можете использовать HTML здесь.',
	'phraseinsertconfirm' => 'Фраза "%s" успешно добавлена',
	'languagejump' => 'Переход Языка',
	'language' => 'Язык перевода',
	'deletephrase' => 'Удалить Фразу',
	'phrasedeleteconfirm' => 'Фраза "%s" успешно удалена',
	'phrasedeletepopup' => 'Вы уверены, что хотите удалить эту фразу? Удаление фраза может изменить способ отображения шаблонов!',
	'phrasedelfailure' => 'ОШИБКА: Не удается удалить фразу',
	'novalue' => '[Нет Главного Доступного Значения]',
);
?>