<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array(
	'tsticketid' => 'ID Тикета',
	'desc_tsticketid' => '',
	'tsticketmaskid' => 'ID Маски Тикета',
	'desc_tsticketmaskid' => '',
	'tsfullname' => 'Полное имя',
	'desc_tsfullname' => '',
	'tsemail' => 'Email',
	'desc_tsemail' => '',
	'tslastreplier' => 'Последний Ответивший',
	'desc_tslastreplier' => '',
	'tsreplyto' => 'Ответить',
	'desc_tsreplyto' => 'Адрес email для ответов, как указано в заголовке email. Используется только для тикетов, созданных через e-mail.',
	'tssubject' => 'Тема',
	'desc_tssubject' => '',
	'tsmessage' => 'Сообщение',
	'desc_tsmessage' => 'Тело тикета. Используется поисковая система n-gram.',
	'tsmessagelike' => 'Сообщение (SQL LIKE)',
	'desc_tsmessagelike' => 'Тело тикета. спользуется поисковая система SQL LIKE.',
	'tsuser' => 'Пользователь',
	'desc_tsuser' => '',
	'tsuserorganization' => 'Организация Пользователя',
	'desc_tsuserorganization' => '',
	'tsipaddress' => 'IP адрес',
	'desc_tsipaddress' => '',
	'tscharset' => 'Кодировка',
	'desc_tscharset' => 'Кодировка Тикета.',
	'tsphone' => 'Телефон',
	'desc_tsphone' => '',
	'tstimeworked' => 'Время, потраченное на работу',
	'desc_tstimeworked' => 'Общее потраченное время (в секундах).',
	'tstimebilled' => 'Оплачиваемое время',
	'desc_tstimebilled' => 'Общее оплачиваемое время (в секундах).',
	'tsdepartment' => 'Подразделение',
	'desc_tsdepartment' => '',
	'tsowner' => 'Исполнитель',
	'desc_tsowner' => '',
	'tstype' => 'Тип',
	'desc_tstype' => '',
	'tsstatus' => 'Статус',
	'desc_tsstatus' => '',
	'tspriority' => 'Приоритет',
	'desc_tspriority' => '',
	'tsemailqueue' => 'Email Очередь',
	'desc_tsemailqueue' => '',
	'tsslaplan' => 'SLA план',
	'desc_tsslaplan' => '',
	'tsflag' => 'Флаг',
	'desc_tsflag' => '',
	'tstemplategroup' => 'Группа Шаблонов',
	'desc_tstemplategroup' => '',
	'tsescalation' => 'Повышение',
	'desc_tsescalation' => '',
	'tsbayesian' => 'Базовый',
	'desc_tsbayesian' => '',
	'tsusergroup' => 'Группа Пользователей',
	'desc_tsusergroup' => '',
	'tscreator' => 'Автор',
	'desc_tscreator' => '',
	'tscreationmode' => 'Метод создания',
	'desc_tscreationmode' => '',
	'tsdue' => 'Актуальность',
	'desc_tsdue' => '',
	'tsduerange' => 'Актуальность <диапазон>',
	'desc_tsduerange' => '',
	'tsresolutiondue' => 'Актуальность решения',
	'desc_tsresolutiondue' => '',
	'tsresolutionduerange' => 'Актуальность решения <диапазон>',
	'desc_tsresolutionduerange' => '',
	'tscreationdate' => 'Дата создания',
	'desc_tscreationdate' => '',
	'tscreationdaterange' => 'Дата создания <диапазон>',
	'desc_tscreationdaterange' => '',
	'tslastactivity' => 'Последняя активность',
	'desc_tslastactivity' => '',
	'tslastactivityrange' => 'Последняя активность <диапазон>',
	'desc_tslastactivityrange' => '',
	'tslaststaffreply' => 'Последний ответ Работника',
	'desc_tslaststaffreply' => '',
	'tslaststaffreplyrange' => 'Последний ответ Работника <диапазон>',
	'desc_tslaststaffreplyrange' => '',
	'tslastuserreply' => 'Последний ответ Пользователя',
	'desc_tslastuserreply' => '',
	'tslastuserreplyrange' => 'Последний ответ Пользователя <диапазон>',
	'desc_tslastuserreplyrange' => '',
	'tsescalateddate' => 'Дата обострения',
	'desc_tsescalateddate' => '',
	'tsescalateddaterange' => 'Дата обострения <диапазон>',
	'desc_tsescalateddaterange' => '',
	'tsresolutiondate' => 'Дата решения',
	'desc_tsresolutiondate' => '',
	'tsresolutiondaterange' => 'Дата решения <диапазон>',
	'desc_tsresolutiondaterange' => '',
	'tsreopendate' => 'Дата повторного открытия',
	'desc_tsreopendate' => '',
	'tsreopendaterange' => 'Дата повторного открытия <диапазон>',
	'desc_tsreopendaterange' => '',
	'tsedited' => 'Редактировалось?',
	'desc_tsedited' => '',
	'tseditedby' => 'Редактировал',
	'desc_tseditedby' => '',
	'tsediteddate' => 'Дата Редактирования',
	'desc_tsediteddate' => '',
	'tsediteddaterange' => 'Дата Редактирования <диапазон>',
	'desc_tsediteddaterange' => '',
	'tstotalreplies' => 'Ответов в общем',
	'desc_tstotalreplies' => '',
	'tshasnotes' => 'Есть Заметки?',
	'desc_tshasnotes' => '',
	'tshasattachments' => 'Есть вложенные файлы?',
	'desc_tshasattachments' => '',
	'tsisemailed' => 'Отправлено на почту?',
	'desc_tsisemailed' => '',
	'tshasdraft' => 'Есть Черновики?',
	'desc_tshasdraft' => '',
	'tshasfollowup' => 'Есть просмотры?',
	'desc_tshasfollowup' => '',
	'tsislinked' => 'Связанный?',
	'desc_tsislinked' => '',
	'tsisfirstcontactresolved' => 'Первое сообщение решило проблему?',
	'desc_tsisfirstcontactresolved' => '',
	'tsaverageresponsetime' => 'Среднее время отклика',
	'desc_tsaverageresponsetime' => '',
	'tsescalationlevelcount' => 'Уровень обострения',
	'desc_tsescalationlevelcount' => '',
	'tswasreopened' => 'Был заново открыт?',
	'desc_tswasreopened' => '',
	'tsisresolved' => 'Вопрос решен?',
	'desc_tsisresolved' => '',
	'tsresolutionlevel' => 'Уровень Решения',
	'desc_tsresolutionlevel' => '',
	'tsticketnotes' => 'Заметки Тикета',
	'desc_tsticketnotes' => '',

	/**
	 * ---------------------------------------------
	 * OTHER LOCALES
	 * ---------------------------------------------
	 */
	'notapplicable' => '-- Не применимо --',
	'lookup' => 'Просмотр',
);
?>
