<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titleduplicatesgroup' => 'Копия Названия Группы',
	'msgduplicatesgroup' => SWIFT_PRODUCT . ' не может вставить групу, так как уже существует группа с таким именем.',
	'depnotassigned' => '(Не назначено)',
	'tabskills' => 'Навыки',
	'noskillstodisplay' => 'Нет доступных навыков. Перейдите в Live Chat &gt; Insert Skill to add skills.',
	'titleextinvalid' => 'Неправильное приложение',
	'msgextinvalid' => 'Вы ввели неправильное приложение. Пожалуйста убедитесь, что приложение, которые Вы ввели цыфровое и не имеет специальных символов.',
	'livechatoptions' => 'Настройки Live Chat',
	'lcgreeting' => 'Авто приветсвие',
	'desc_lcgreeting' => 'Впишие приветсвенное сообщение, которые будет отображатся при том, когда работник начнет чат с клиентом.',
	'titleinvalidfileext' => 'Неправильное Изображение',
	'msginvalidfileext' => 'Файл изображение имеет неправильное разширение. Разрешенные расширения: gif, jpeg, jpg, png',
	'rrenabled' => 'RingRoute включено',
	'desc_rrenabled' => 'Укажите должен ли функционал RingRoute быть доступен для этого работника.',
	'rrextension' => 'RingRoute Extension',
	'desc_rrextension' => 'Введите RingRoute extension номер для работника.',
	'personalizeoptions' => 'Редактировать',
	'generaloptions' => 'Общие настройки',
	'staffprofileimage' => 'Изображение профиля',
	'desc_staffprofileimage' => 'Загрузите изображение в профиль работника. Данное изображение будет отображено в тикет-сообщениях, а также в окне чата.',
	'ringrouteoptions' => 'RingRoute настройки',
	'tabprofile' => 'Профиль',
	'stafffirstname' => 'Имя',
	'desc_stafffirstname' => '',
	'stafflastname' => 'Фамилия',
	'desc_stafflastname' => '',
	'staffdesignation' => 'Должность',
	'desc_staffdesignation' => 'Укажите должность работника, которая будет указана в тикет-сообщениях. а также в чате. Например: Саппорт менеджер, Финансовый менеджер.',
	'titleemailqueuematch' => 'Ошибка при вводе Email',
	'msgemailqueuematch' => 'Этот email адрес "%s" уже используется как e-mail очереди.',
	'titlemobilenumberinvalid' => 'Неправильный номер мобильного телефона',
	'msgmobilenumberinvalid' => 'Введенный номер мобильного телефона неправильный. Пожалуйста, введите только цыфры, без "+", а также разделителей номера.',
	'copyfrom' => 'Скопировать полномочия',
	'titleinsertstaff' => 'Добавленый работник "%s" (%s)',
	'msginsertstaff' => 'Успешно добавлен работник "<b>%s</b>"<br /><b>Полное имя:</b> %s<br /><b>Логин:</b> %s<br /><b>Email:</b> %s<br /><b>Команда:</b> %s<br /><b>Включен:</b> %s<br /><b>Номер мобильного:</b> %s<br /><b>Использовать командные подразделения?:</b> %s',
	'titleupdatestaff' => 'Обновлен Работник "%s" (%s)',
	'msgupdatestaff' => 'Успешно обновлен работник "<b>%s</b>"<br /><b>Полное имя:</b> %s<br /><b>Логин:</b> %s<br /><b>Email:</b> %s<br /><b>Команда:</b> %s<br /><b>Включен:</b> %s<br /><b>Номер мобильного:</b> %s<br /><b>Использовать командные подразделения?:</b> %s',
	'titlepwnomatch' => 'Неправильный пароль',
	'msgpwnomatch' => 'Введенный пароль не совпадает.',
	'titlenodep' => 'Не назначено подразделение',
	'msgnodep' => 'Пожалуйста, назначте работнику подразделения.',
	'titleusernameexists' => 'Имя пользователя не соответсвует',
	'msgusernameexists' => 'Имя пользователя "%s" уже используется работником "%s". Введите другое имя пользователя для продолжения.',
	'titlegrouperror' => 'Ошибка в команде, продолжение невозможно.',
	'msggrouperror' => 'You cannot change the team to a Non-Admin Team as this Staff is the only one with admin privileges.',
	'titlestaffdelsame' => 'Не удается удалить',
	'msgstaffdelsame' => 'Невозможно удалить пользователя, который в данный момент находится в системе. Пожалуйста, войдите под другим именем для удаления "%s".',
	'titledelstaffmul' => 'Удален работник "%d"',
	'msgdelstaffmul' => 'Успешно удалены следующие работники:<br />%s',
	'titledelstaff' => 'Удален работник "%s" (%s)',
	'msgdelstaff' => 'Работник "%s" (%s) успешно удален из базы.',
	'titleinsertstaffgroup' => 'Создана команда "%s"',
	'msginsertstaffgroup' => 'Команда "<b>%s</b>"<br /><b>Название:</b> %s<br /><b>Являются ли администраторами:</b> %s<br /><b>Назначенный Подразделения:</b> %s успешно создана',
	'titleupdatestaffgroup' => 'Обновлена Команда "%s"',
	'msgupdatestaffgroup' => 'Команда "<b>%s</b>"<br /><b>Название:</b> %s<br /><b>Являются ли администраторами:</b> %s<br /><b>Назначенный Подразделения:</b> %s успешно создана',
	'titlestaffgroupdelsame' => 'Невозможно удалить',
	'msgstaffgroupdelsame' => 'Не удается удалить выбранную команду, т.к. она назначена для пользователя, который в данный момент находится в системе. Для удаления команды, пожалуйста войдите под другим логином "%s".',
	'titledelstaffteammul' => 'Удалена(ы) "%d" команда(ы)',
	'msgdelstaffteammul' => 'Следующая(и) Команда(ы) успешно удалены:<br />%s',
	'titledelstaffteam' => 'Удаленная(ые) Команда(ы) "%s"',
	'msgdelstaffteam' => 'Команда "%s" (%s) успешно удалена.',
	'loginshare' => 'LoginShare',
	'tabsettings' => 'Настройки',
	'tabplugins' => 'Плагины',
	'ls_module' => 'LoginShare плагины',
	'wineditls' => 'Редактировать настройки LoginShare: %s',
	'lsnotitle' => 'Нет доступных настроек',
	'lsnomsg' => 'Нет доступных настроек для LoginShare плагина <b>"%s"</b>.',
	'tabmassmail' => 'Массовая почта',
	'tabfilter' => 'Фильтр',
	'filterbyteams' => 'Фильтровать по Командах',
	'filterbystaff' => 'Фильтровать по Работниках',
	'send' => 'Отправить',
	'isenabled' => 'Включено?',
	'desc_isenabled' => 'Переключить состояние Работника. Отключенные Работники не могут входить в панель управления или осуществлять другие действия.',
	'assigneddepartments' => 'Призначенные Подразделения',
	'titlenoenable' => 'Невозможно Отключить "%s"',
	'msgnoenable' => 'Вы не можете отключить пользователя "%s", который находится онлайн. Пожалуйста, войдите под другим пользователем.',
	'titledisablestaff' => 'Отключен Работнки "%d"',
	'msgdisablestaff' => 'Успешно отключены следующие Работники:<br />%s',
	'titleenablestaff' => 'Включен Работник "%d"',
	'msgenablestaff' => 'Успешно включены следующие Работники:<br />%s',
	'titleupdatedsettings' => 'Обновлены настройки "%s"',
	'msgupdatedsettings' => 'Успешно обновлены настройки категории "%s" пользователя "%s"',
	'titleselectonerecord' => 'Не выбран Работник/Команда',
	'msgselectonerecord' => 'Вы должны выбрать как минимум одного Работника/Команду для отправки Массовой Почты.',
	'titlemassmailsent' => 'Почта отправлена Работнику "%d"',
	'msgmassmailsent' => 'Почта успешно отправлена следующим Работникам:',
	'attachments' => 'Приложеные файлы',
	'tabimport' => 'Импорт',
	'loginsharefile' => 'LoginShare XML File',
	'desc_loginsharefile' => 'Загрузите LoginShare XML файл',
	'ignoreversion' => 'Игнорировать версию',
	'desc_ignoreversion' => 'Если включена, версия импортированого файла будет игнорироватся. Рекомендуется не включать эту опцию, из-за возможности возникновения проблем в Центре Поддержка Клиентов.',
	'import' => 'Импорт',
	'titlenoelevatedls' => 'Невозможно импортировать LoginShare XML Работников',
	'msgnoelevatedls' => SWIFT_PRODUCT.' не может импортировать Staff LoginShare XML файл, т.к. требуется чтоб Вы вошли в качестве пользователя, у которого права выше. Вы можете добавить права Вашему пользователю в файле config/config.php.',
	'titlelsversioncheckfail' => 'Не удалось Проверить Версию',
	'msglsversioncheckfail' => SWIFT_PRODUCT. ' не может импортировать Staff LoginShare плагин, т.к. плагин разработан для старой версии '.SWIFT_PRODUCT,
	'titlelsinvaliduniqueid' => 'Ошибка из-за совпадения ID',
	'msglsinvaliduniqueid' => SWIFT_PRODUCT .' не может импортировать Staff LoginShare плагин из-за конфликта ID. Как правило это означает, что плагин уже был добавлен.',
	'titlelsinvalidxml' => 'Неверный XML файл',
	'msglsinvalidxml' => SWIFT_PRODUCT .' не может импортировать Staff LoginShare плагин т.к. XML файл испорчен или местит в себе неправильные данные.',
	'titlelsimported' => 'Испортированый Staff LoginShare плагин',
	'msglsimported' => SWIFT_PRODUCT .' успешно импортирован "%s" Staff LoginShare плагин.',
	'titlelsdeleted' => 'Удален Staff LoginShare плаигн',
	'msglsdeleted' => 'Успешно удален "%s" Staff LoginShare плагин.',
	'invalidloginshareplugin' => 'Неправильный плагин LoginShare, проверьте пожалуйста что плагин LoginShare существует в базе.',
	'titleupdatedls' => 'Обновлены Staff LoginShare настройки',
	'msgupdatedls' => 'Успешно обновлены настройки "%s" Staff LoginShare плагин',
	'tabpermissionsstaff' => 'Разрешения: Работники',
	'tabpermissionsadmin' => 'Разрешения: Админ',
	'iprestriction' => 'Ограничить IP',
	'desc_iprestriction' => 'Вы можете ограничить, откуда Работник может войти по IP или подсети. Напишите IP адреса через кому \',\'. Пример:<BR /><i> * <b>202.1.192.0-202.1.192.255</b>: Диапазон IP<BR /> * <b>200.36.161.0/24</b>: Несколько IP под одной маской<BR /> * <b>200.36.161/24</b>: </i>',
	'tzusedefault' => '-- Использовать стандартные --',
	'stafftimezone' => 'Временной пояс',
	'desc_stafftimezone' => 'Выберить нужный Часовой пояс для Работников. При выборе Часового пояса здесь, он перепишет стандартный Часовой Пояс.',
	'staffenabledst' => 'Включить переход на летнее время',
	'desc_staffenabledst' => 'Хотите ли Вы использовать переход на летнее время.',
	// ======= END v4 LOCALES =======
	'staff' => 'Работники',
	'desc_staff' => '',
	'managestaff' => 'Управлять Работниками',

	// Staff List
	'stafflist' => 'Список Работников',
	'fullname' => 'Полное Имя',
	'staffgroup' => 'Команда',
	'staffdeletefailedsame' => 'Вы не можете удалить собственный аккаунт. Войдите под другим пользователем для удаления "%s"',
	'staffdeleteconfirm' => 'Работник "%s" успешно удален',
	'wineditstaff' => 'Редактировать Работников',
	'tabedit' => 'Редактировать',
	'tabinsert' => 'Добавить',
	'tabdepartments' => 'Призначенные Подразделения',
	'taboptions' => 'Опции',
	'permissions' => 'Разрешения',
	'wineditteam' => 'Редактировать Команду',

	// Staff Group
	'staffgroups' => 'Команды',
	'managegroups' => 'Управлять Командами',
	'isadmin' => 'Является Администратором?',
	'sgroupdeletefailedsame' => 'Вы не можете удалить Команду, к которой принадлежит Ваш аккаунт. Войдите под другим пользователем для удаления "%s"',
	'sgroupdeleteconfirm' => 'Команда "%s" успешно удалена',
	'sgroupactionconfirm' => 'Важно: При удалении Команды, все аккаунты, которые ей принадлежат буду удалены! Вы уверены что хотите удалить?',

	// Insert Staff
	'insertstaff' => 'Добавить Работника',
	'staffdetails' => 'Детали Работника',
	'stafffullname' => 'Полное имя',
	'desc_stafffullname' => 'Полное имя Работника (например <i>Иванов Иван</i>).',
	'staffusername' => 'Имя Пользователя',
	'desc_staffusername' => 'Имя пользователя Работника. Будут использовать для входа в панель управления.',
	'staffpassword' => 'Пароль',
	'desc_staffpassword' => 'Пароль для Работника.',
	'staffpasswordconfirm' => 'Подтверждение Пароля',
	'desc_staffpasswordconfirm' => 'Для подтверждение, повторите пароль.',
	'staffemail' => 'Email',
	'desc_staffemail' => 'Email адрес Работника. Все оповещения Работнику, будут отправлять на этот адрес.',
	'staffgroup' => 'Команда',
	'desc_staffgroup' => 'Выберите Команду, к которой будет принадлежать Работник. Будут использованы все настройки выбранной Команды.',
	'optionalfields' => 'Дополнительные поля',
	'staffmobilenumber' => 'Номер Мобильного',
	'desc_staffmobilenumber' => 'Если Работник хочет получать оповещения через смс, введите номер мобильного. Примечание: введите только цыфры без разделителей и пробелов.<br/>Например: <i>\'18005551212\'</i> ',
	'staffsignature' => 'Подпись',
	'desc_staffsignature' => 'Введите подпись для Работника. Она будет использована во всях исходящих письмах.',
	'staffassigneddep' => 'Назначенные Подразделения',
	'usegroupdep' => 'Использовать Подразделения Команды',
	'desc_usegroupdep' => 'Если включено, натройки Подразделений, выбраной команды, будут присвоены пользователю.',
	'assigneddep' => 'Назначенные Подразделения',
	'desc_assigneddep' => 'Выберите индивидуальные разрешения отдела, если выбрана опция выше.',
	'passworddontmatch' => 'Введенные пароли не совпадают',
	'usernameexists' => 'Данное имя пользователя для работника уже используется',
	'selectdepartment' => 'Вы должны назначить Работнику хотя бы одно подразделение',
	'redirect_staffinsert' => 'Работник успешно добавлен',
	'staffinsertconfirm' => 'Работник "%s" успешно добавлен',

	// Edit Staff
	'updatestaff' => 'Обновить Работника',
	'editstaff' => 'Редактировать Работника',
	'invalidstaff' => 'Ошибка: неправильный ID Работника',
	'desc_staffpasswordedit' => 'Если Вы хотите сменить пароль, введите эго здесь.',

	// Insert Staff Group
	'insertstaffgroup' => 'Добавить Команду',
	'staffgroupdetails' => 'Детали Команды',
	'generalfields' => 'Общие Поля',
	'grouptitle' => 'Название',
	'desc_grouptitle' => 'Введите Название Команды.',
	'groupisadmin' => 'Администратор',
	'desc_groupisadmin' => 'Если включено, это команда будет администрацией и сможет входить в <b>эту</b> панель управления, а также иметь более широкий круг возможнотей.',
	'groupassigneddep' => 'Призначенные Подразделения',
	'desc_groupassigneddep' => 'Выберите Подразделение (или несколько) к которым будет призначен работник.',
	'redirect_staffgroupinsert' => 'Команда успешно добавлена',
	'staffgroupinsertconfirm' => 'Команда "%s" успешно добавлена',

	// Edit Staff
	'staffupdateconfirm' => 'Работник "%s" успешно обновлен',
	'grouperror' => 'Вы не можете сменить команду на не-административную команду, т.к. она только одна',

	// Edit Staff Group
	'editstaffgroup' => 'Редактировать Команду',
	'invalidstaffgroup' => 'Неправильная Команда',
	'staffgroupupdateconfirm' => 'Группа "%s" успешно обновлена',
	'groupadminerror' => 'Вы не можете отключить права администратора для этой команды, т.к. она одна, которая имеет эти права',

	// Mass Mail
	'massmail' => 'Массовая Почта',
	'subject' => 'Тема',
	'desc_subject' => '',
	'send' => 'Отправить',
	'mailcontents' => 'Содержание Почты',
	'mailstaffgroup' => 'Команда',
	'desc_mailstaffgroup' => '',
	'selectonegroup' => 'Ошибка: выберите хотя бы одну Команду',
	'sentmailconfirm' => 'Почта отправлена работникам %s',
	'mmcontents' => 'Содержание Почты',

	// License
	'titlestafflicense' => 'Превышен Лимит Лицензии',
	'msgstafflicense' => SWIFT_PRODUCT . ' невозможно добавить нового работника т.к. Вы достигли лимит, предусмотреный в лицензии. Свяжитесь с Kayako Support здесь <a href="https://my.kayako.com" target="_blank">https://my.kayako.com</a>.',

);

?>