<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array(
	'manage' => 'Управление',

	'tabgeneral' => 'Общее',
	'tabmassaction' => 'Массовые действия',
	'tabreply' => 'Ответить',
	'tabforward' => 'Перенаправить',

	'manochange' => '-- Без изменений --',
	'maticketstatus' => 'Статус Тикета',
	'maticketpriority' => 'Приоритет Тикета',
	'matickettype' => 'Тип Тикета',
	'madepartment' => 'Подразделение',
	'maowner' => 'Исполнитель',
	'maticketlink' => 'Связь',
	'maaddtags' => 'Добавить теги',
	'maremovetags' => 'Удалить теги',
	'maticketflag' => 'Флаг',
	'manoflag' => '-- Без Флага --',
	'mabayescategory' => 'Train Bayesian',
	'sactivestaff' => '-- Активный Персонал --',
	'tnavnextticket' => 'Следующий Тикет &raquo;',
	'tnavprevticket' => '&laquo; Предыдущий Тикет',

	/**
	 * ---------------------------------------------
	 * Viewing a Ticket
	 * ---------------------------------------------
	 */
	'mergeoptions' => 'Параметры слияния',
	'mergeparentticket' => 'ID предыдущего Тикета',
	'desc_mergeparentticket' => 'Если выбрано, текущий тикет будет объединен с выбранным.',
	'titleeditmergefailed' => 'Ошибка при объединении Тикетов',
	'msgeditmergefailed' => SWIFT_PRODUCT . ' несмог объединить тикет, из-за того, что исходный тикет может не находится в базе данных. Пожалуйста, проверьте ID указанного тикета.',
	'titleeditmergesuccess' => 'Тикет успешно объединен',
	'msgeditmergesuccess' => SWIFT_PRODUCT . ' успешно объединил тикет.',
	'putback' => 'Положить обратно',
	'tabcalls' => 'Звонки',
	'dispatchasuser' => 'Как пользователь',
	'viewticket' => 'Отобразить Тикет',
	'viewticketext' => '[#%s]: %s',
	'proptitleticketid' => 'ID Тикета',
	'proptitledepartment' => 'Подразделение',
	'proptitleowner' => 'Исполнитель',
	'proptitlestatus' => 'Статус',
	'proptitlepriority' => 'Приоритет',
	'proptitletype' => 'Тип',
	'tinforesolutiondue' => 'Актуальность решения: ',
	'tinfosla' => 'SLA: ',
	'tinfoticketid' => 'ID: ',
	'tinfodue' => 'Актуально: ',
	'tinfocreated' => 'Создан: ',
	'tinfoupdated' => 'Обновлен: ',
	'ticketlinkinfo' => 'Подразделение: %s, Статус: %s',
	'tppostedon' => 'Размещен: %s',
	'tppostedonsurvey' => 'Обзорный Комментарий размещен: %s',
	'tpemail' => 'Email: %s',
	'tpipaddress' => 'IP адрес: %s',
	'participantbox' => 'Участники',
	'badgethirdparty' => 'Посторонние',
	'badgeuser' => 'Пользователь',
	'badgestaff' => 'Работник',
	'badgecc' => 'Получатель',
	'badgebcc' => 'Скрытая копия письма',
	'wineditticketpost' => 'Редактировать Сообщение Тикета',
	'editpost' => 'Редактировать Сообщение',
	'lastedited' => 'Последний раз Редактировал: %s На: %s',
	'wineditdue' => 'Редактировать Актуальноть и График Решения',
	'dialogduetimeline' => 'Актуальность',
	'dialogresolutionduetimeline' => 'Актуальность Решения',
	'stopwatching' => 'Прекратить наблюдение',
	'surrender' => 'Отказать',
	'take' => 'Принять',
	'tabauditlog' => 'Журнал Контроля',
	'aldescription' => 'Описание',
	'aldate' => 'Дата',
	'altimeline' => 'График',
	'alentrytype' => 'Тип записи',
	'alstaff' => ' (Работник)',
	'aluser' => ' (Пользователь)',
	'alsystem' => ' (Система)',
	'alparser' => ' (Парсер)',
	'editnote' => 'Редактировать Заметку',
	'notetitle' => '%s на %s',
	'noteeditedtitle' => ' <i>(Отредактировал %s на %s)</i>',
	'ticketnotedelconfirm' => 'Вы уверены что хотите удалить заметку из Тикета?',
	'tabaddnote' => 'Добавить Заметку',
	'tabeditnote' => 'Редактировать Заметку',
	'addnotes' => 'Заметки',
	'notetype' => 'Тип Заметки',
	'addnote' => 'Добавить Заметку',
	'notes_ticket' => 'Тикет',
	'notes_user' => 'Пользователь',
	'notes_userorganization' => 'Организация Пользователя',
	'tabrelease' => 'Опубликовать',
	'tabedit' => 'Редактировать',
	'tabhistory' => 'История',
	'tabchats' => 'Разговоры',
	'tabuser' => 'Пользователь',
	'notesvisibleall' => '-- Все --',
	'notevisibleto' => 'Видимость',
	'desc_notevisibleto' => 'Вы можете использовать эту функцию для запрета просмотра даного тикета любому работнику.',
	'edit_subject' => 'Тема',
	'edit_fullname' => 'Полное Имя',
	'edit_email' => 'Email',
	'edit_overridesla' => 'Аннулировать SLA',
	'desc_edit_overridesla' => 'При включениию, тикет будет следовать текущему SLA.',
	'editslausedef' => '-- Использовать стандартный SLA --',
	'edittproperties' => 'Свойства Тикета',
	'edittrecipients' => 'Получатели Тикета',
	'editrecipientsdesc' => 'Вы можете добавить новых получателей, путем добавления e-mail адреса ниже в соответсвующих полях типов получателей. Добавленый получатель будет автоматичести получать ответы персонала, но не сможет посмотреть тикет онлайн, через интерфейс клиента.<br /><br />Подписчики тикетов также получают все письма, которые были отправлены персоналом. Опция добавления получателей тикетов доступна для отправки Копий, Скрытых копий, а также перенаправленых Тикетов. Существует 3 типа получателей:<br /><br /><i>Посторонние:</i> Сторонние подписчики, получают идентичные копие ответов персонала. Посторонние подписчики могут отвечать через почту только на тикеты, созданные ими.<br /><br /><i>Получатели Копий:</i> Получатели Копий, получают только копии ответов персонала на тикеты.<br /><br /><i>Получатели Скрытых Копий:</i> Получатели Скрытых Копий получают скрытые копии ответов, которые никто не видит кроме них.',
	'editthirdparty' => 'Посторонние',
	'editcc' => 'Копия',
	'editbcc' => 'Скрытая Копия',
	'history_ticketid' => 'ID Тикета',
	'history_subject' => 'Тема',
	'history_date' => 'Дата',
	'history_department' => 'Подразделение',
	'history_type' => 'Тип',
	'history_status' => 'Статус',
	'history_priority' => 'Приоритет',
	'workflowbox' => 'Последовательность Действий',
	'informationbox' => 'Информация',
	'tinfobticketid' => 'ID Тикета',
	'tinfobuser' => 'Пользователь',
	'tinfobuserorganization' => 'Организация',
	'tinfobusergroup' => 'Группа',
	'dispatchfrom' => 'От',
	'dispatchto' => 'Кому',
	'dispatchcc' => 'Копия',
	'dispatchbcc' => 'Скрытая Копия',
	'dispatchcontents' => 'Содержание Ответов',
	'dispatchaddmacro' => 'Макрос',
	'dispatchaddkb' => 'База Знаний',
	'dispatchsendmail' => 'Отправить Письмо',
	'dispatchwatch' => 'Следить',
	'dispatchaddfile' => 'Добавить Файл',
	'dispatchsend' => 'Отправить',
	'dispatchattachfile' => 'Прикрепить',
	'dispatchsaveasdraft' => 'Сохранить',
	'dispatchto' => 'Кому',
	'dispatchsubject' => 'Тема',
	'dispatchsend' => 'Отправить',
	'dispatchsendar' => 'Отправить Автоответчик',
	'dispatchuser' => 'Пользователь',
	'dispatchnewuser' => 'Новый Пользователь',
	'dispatchisphone' => 'Телефонный Тикет',
	'winuserquickinsert' => 'Новый Пользователь',
	'dispatch' => 'Отправка',
	'tabdispatch' => 'Отправить',
	'dispatchticket' => 'Отправить Тикет',
	'assign' => 'Присвоить',
	'newticket' => 'Новый Тикет',
	'newticket_department' => 'Подразделение',
	'desc_newticketdepartment' => 'Выберите подразделение, в каком Вы хотите создать Тикет.',
	'nt_sendmail' => 'Отправить Письмо',
	'nt_asuser' => 'Как Пользователь/Телефон',
	'newticket_type' => 'Тип',
	'desc_newticket_type' => 'Выберить тип создаваемого Тикета.<br /><br /><i>Отправить Письмо:</i> Отправить письмо на выбранный адрес (работает как email клиент)<br /><i>Как Пользователь/Телефон:</i> Создать тикет или журнал входящих звонков от пользователя.',
	'nt_next' => 'Следующий',
	'tabnewticket' => 'Новый Тикет',
	'dispatchcreate' => 'Создать',
	'tabnewticket2' => 'Новый Тикет: %s',
	'tpemailto' => 'Отправить на почту: %s',
	'tpemailforwardedto' => 'Кому перенаправлен: %s',
	'tlockinfo' => '%s просматривает тикет (последнее изменение: %s)',
	'tpostlockinfo' => '%s отвечает на тикет (последнее изменение: %s)',
	'tabbilling' => 'Оплата',
	'tabfollowup' => 'Контролировать',
	'notes' => 'Заметки',
	'billworker' => 'Работник',
	'billdate' => 'Дата Оплаты',
	'billworkdate' => 'Дата Работы',
	'billtimespent' => 'Потраченое время (чч:мм)',
	'billworked' => 'Кто работал:',
	'billtotalworked' => 'Общее время потраченное на работу:',
	'billbillable' => 'Оплаченое время:',
	'billtotalbillable' => 'Общее оплаченое время:',
	'editbilling' => 'Редактировать Оплату',
	'tabeditbilling' => 'Редактировать Оплату',
	'billingtitle' => 'Платежная запись для: %s на %s',
	'billingtitlework' => ' (работал над: %s)',
	'billingeditedtitle' => ' <i>(Отредактировал %s on %s)</i>',
	'billingeditedtitle2' => ' <i>(Отредактирован на %s)</i>',
	'editbilling' => 'Редактировать Платежную Запись',
	'ticketbillingdelconfirm' => 'Вы уверены что хотите удалить Платежную Запись?',
	'titleinvalidbilldate' => 'Неправильное значение Потраченного Времени',
	'msginvalidbilldate' => 'Пожалуйста, выберите правильное значение.',
	'fugeneral' => 'Общее',
	'fuaddnote' => 'Добавить Заметку',
	'fupostreply' => 'Написать Ответ',
	'fuforward' => 'Перенаправить',
	'followupmins' => 'В минутах',
	'followuphours' => 'В часах',
	'followupdays' => 'В днях',
	'followupweeks' => 'В неделях',
	'followupmonths' => 'В месяцах',
	'followupcustom' => 'Свои',
	'followup' => 'Контролировать',
	'currentfollowups' => 'Действующие контроли за тикетом:',
	'followup_willrunattime' => 'Запустит контроль над %s создан %s (%s)',
	'followup_willchangeownerto' => 'Изменит исполнителя на %s',
	'followup_willchangedepartmentto' => 'Изменит подразделение на %s',
	'followup_willchangestatusto' => 'Изменит статус на %s',
	'followup_willchangepriorityto' => 'Изменит приоритет на %s',
	'followup_willchangetypeto' => 'Изменит тип на %s',
	'followup_willaddstaffnotes' => 'Добавить заметку к Тикету',
	'followup_willaddusernotes' => 'Добавит Заметку пользователя',
	'followup_willaddareply' => 'Добавит заготовленный ответ к тикету',
	'followup_willforwardto' => 'Перенаправит тикет на %s',
	'followup_removeowner' => 'Удалит текущего исполнителя тикета',
	'flag' => 'Флаг',
	'tescalationhistory' => 'Посмотреть историю развития (%d)',
	'tepdate' => 'Дата развития: ',
	'tepslaplan' => 'SLA план: ',
	'tepescalationrule' => 'Правило развития: ',
	'ntchatid' => 'ID чата: ',
	'ntchatuserfullname' => 'Пользователь: ',
	'ntchatuseremail' => 'Email: ',
	'ntchatstafffullname' => 'Работник: ',
	'ntchatdepartment' => 'Подразделение: ',
	'titleticketdeleted' => 'Тикет Удален',
	'msgticketdeleted' => 'Невозможно загрузить тикет, тикет удален',

	/**
	 * ---------------------------------------------
	 * MACRO
	 * ---------------------------------------------
	 */
	'macro' => 'Добавить Макрос',
	'macros' => 'Макрос',
	'insertmacro' => 'Добавить Макрос',
	'editmacro' => 'Редактировать Макрос',
	'tabcategories' => 'Категории',
	'tabreplies' => 'Ответы',
	'replytitle' => 'Название Ответа',
	'macrotitle' => 'Название Макроса',
	'insertcategory' => 'Добавить Категорию',
	'insertreply' => 'Добавить Ответ',
	'wininsertmacrocat' => 'Добавить Категорию Макроса',
	'parentcategoryitem' => '- Корневая категория -',
	'macrocategorytitle' => 'Название Категории',
	'desc_macrocategorytitle' => 'Введите название категории.',
	'parentcategory' => 'Корневая категория',
	'desc_parentcategory' => 'Категорию, в которую будет добавлена создаваемая категория. Вы можете использовать неограниченую иерархию категорий.',
	'categorytype' => 'Тип Категории',
	'desc_categorytype' => '<i>Публичная:</i> Видимая для всех работников.<BR /><BR /><i>Приватная:</i> Видимая только для создателей.',
	'titlemacrocategoryinsert' => 'Добавлена Категория Макросов "%s"',
	'msgmacrocategoryinsert' => SWIFT_PRODUCT . ' успешно добавлена Категория Макросов "%s".',
	'titlemacrocategoryupdate' => 'Обновлена Категория Макросов "%s"',
	'msgmacrocategoryupdate' => SWIFT_PRODUCT . ' успешно обновлена Категория Макросовy "%s".',
	'titleinvalidparentcat' => 'Неправильна Корневая Категория',
	'msginvalidparentcat' => 'Выбрана неправильная корневая категория. Пожалуйста, проверьте дерево категорий на предмет правильности.',
	'titledelmacrocat' => 'Удалены "%d" Макро Категории',
	'msgdelmacrocat' => SWIFT_PRODUCT . ' успешно удалены следующие макро категоии:',
	'filterreplies' => 'Фильтровать Ответы',
	'rootcategory' => 'Корневая категория',
	'macroreplytitle' => 'Название Макроса',
	'desc_macroreplytitle' => 'Введите название макроса ответа.',
	'parentcategoryreply' => 'Исходная Категория',
	'desc_parentcategoryreply' => 'Категория, в которой будет добавлен ответ.',
	'reststaffgroupall' => '-- Все Команды Персонала --',
	'restrictstaffgroup' => 'Видимая для',
	'desc_restrictstaffgroup' => 'Вы можете запретить видимость для выбраных категорий персонала.',
	'macroreplycontents' => 'Содержание Ответов',
	'tabproperties' => 'Свойства',
	'ticketfields' => 'Свойства Тикета',
	'macrodepartment' => 'Подразделение',
	'desc_macrodepartment' => '',
	'macroticketstatus' => 'Статус Тикета',
	'desc_macroticketstatus' => '',
	'macrotickettype' => 'Тип Тикета',
	'desc_macrotickettype' => '',
	'macroticketpriority' => 'Приоритет Тикета',
	'desc_macroticketpriority' => '',
	'desc_macroaddtags' => '',
	'macroaddtags' => 'Добавить теги',
	'macroownerstaff' => 'Иполнитель Тикета',
	'desc_macroownerstaff' => '',
	'insertmacro' => 'Добавить Макрос',
	'editmacro' => 'Редактировать Макрос',
	'titlemacroreplyinsert' => 'Добавлен Макрос "%s"',
	'msgmacroreplyinsert' => SWIFT_PRODUCT . ' успешно добавлен Макрос "%s".',
	'titlemacroreplyupdate' => 'Обновлен Макрос "%s"',
	'msgmacroreplyupdate' => SWIFT_PRODUCT . ' успешно обновлен Макрос "%s".',
	'titledelmacroreply' => 'Удалены "%d" Макросы ответов',
	'msgdelmacroreply' => SWIFT_PRODUCT . ' успешно удалены следующие макросы ответов:',
	'quickinsert' => 'Быстрое Добавление',
	'qimacro' => 'Макрос',
	'qiknowledgebase' => 'База Знаний',
	'qidownloads' => 'Загрузки',
	'replytotalhits' => 'Просмотры',
	'replylastused' => 'Последнее использование',


	/**
	 * ---------------------------------------------
	 * SEARCH
	 * ---------------------------------------------
	 */
	'search' => 'Поиск',
	'tabsearch' => 'Расширенный Поиск',
	'matchtype' => 'Опции критериев поиск',
	'desc_matchtype' => 'Выберите метод групировки поисковых критерий.',
	'smatchall' => 'Со всеми словами (и)',
	'smatchany' => 'С любым из слов (или)',
	'insertcriteria' => 'Добавить Критерий',

	/**
	 * ---------------------------------------------
	 * NEW TICKET
	 * ---------------------------------------------
	 */
	'tabrecurrence' => 'Повторение',
	'recurrence_none' => 'Без повторения',
	'recurrence_daily' => 'Ежедневно',
	'recurrence_weekly' => 'Еженедельно',
	'recurrence_monthly' => 'Ежемесячно',
	'recurrence_yearly' => 'Ежегодно',
	'rec_every' => 'Каждые',
	'rec_days' => 'дня',
	'rec_everyweekday' => 'Каждый будний день',
	'rec_weeks' => 'недель',
	'rec_monday' => 'Понедельник',
	'rec_tuesday' => 'Вторник',
	'rec_wednesday' => 'Среда',
	'rec_thursday' => 'Четверг',
	'rec_friday' => 'Пятница',
	'rec_saturday' => 'Суббота',
	'rec_sunday' => 'Воскресение',
	'rec_day' => 'День',
	'rec_ofevery' => 'каждого',
	'rec_months' => 'месяца',
	'rec_the' => '',
	'rec_first' => 'Первый',
	'rec_second' => 'Второй',
	'rec_third' => 'Третий',
	'rec_fourth' => 'Четвертый',
	'rec_fifth' => 'Пятый',
	'rec_of' => 'из',
	'recurnotactivated' => 'Повторение не влючено',
	'recurrencerange' => 'Пределы повторения',
	'recur_starts' => 'Начаниется',
	'recur_ends' => 'Заканчивается',
	'rec_noeenddate' => 'Без даты окончания',
	'rec_endafter' => 'Конец после:',
	'rec_endby' => 'Конец после:',
	'rec_occurrences' => 'повторений',
);

?>
