<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'titlepersonalization' => 'Иформация обновлена',
	'msgpersonalization' => SWIFT_PRODUCT . ' обновил Персональную информация. Вам нужно обновить страницу, чтобы увидеть результаты.',
	'tabpersonalize' => 'Настроить',
	'generalinformation' => 'Общая информация',
	'companyname' => 'Название Компании',
	'desc_companyname' => 'Введенное здесь название используется для брендинга интерфейса клиента и исходящих писем.',
	'defaultreturnemail' => 'Стандартный Email с которого будут отправлены письма',
	'desc_defaultreturnemail' => 'Этот адресс используется как стандартное поле "От кого" в исходящих письмах. Этот адресс должен существовать для принятия ответов от клиентов.',
	'logoimages' => 'Изображения Шапки',
	'supportcenterlogo' => 'Шапка Центра Поддержки',
	'desc_supportcenterlogo' => 'Вы можете редактировать изображение шапки Центра Поддержки, путем загрузки нового файла (gif/jpeg/png). Максимальная высота: 70 px',
	'stafflogo' => 'Шапка Рабочей/Администраторской/PDA панель управления',
	'desc_stafflogo' => 'Вы можете редактировать Шапку Рабочей/Администраторской/PDA панель управления путем загрузки нового файла (gif/jpeg/png). Максимальная высота: 70 px<br /><br /><i>Примечание: Вы должны перезагрузить страницу полностью (Ctrl+F5 или Command+R) для того, чтобы увидеть результат.</i>',
	'personalize' => 'Редактировать',
	'changegroup' => 'Изменить группу',
	'desc_importexport' => '',
	'tabexport' => 'Экспортировать',
	'export' => 'Экспортировать',
	'tabimport' => 'Импортировать',
	'import' => 'Импортировать',
	'result' => 'Результат',
	'titleisenabledprob' => 'Невозможно продолжить',
	'msgisenabledprob' => 'Вы не можете отключить Стандартну Группу Шаблонов.',
	'useloginshare' => 'Использовать LoginShare',
	'desc_useloginshare' => 'Если включено, полномочия пользователей будут проверены через LoginShare API.',
	'exporthistory' => 'Экспортировать История Шаблонов',
	'desc_exporthistory' => 'Если включено, '. SWIFT_PRODUCT.' экспортирует полную историю шаблона, вместе с начальныи данными.',
	'mergeoptions' => 'Объединить опции',
	'addtohistory' => 'Добавить в Историю',
	'desc_addtohistory' => 'Если включено, старые шаблоны будут сохранены в историю шаблонов для ссылки на объедененную группу шаблонов.',
	'titleversioncheckfail' => 'Ошибка при проверке версии',
	'msgversioncheckfail' => SWIFT_PRODUCT. ' не может импортировать пакет шаблонов, т.к. он был создан для старых версий '.SWIFT_PRODUCT,
	'desc_restoretemplates' => '',
	'tabgeneral' => 'Общие',
	'restoretemplatestatus' => 'Статус Шаблона',
	'restoretgroup' => 'Группа Шаблона: %s',
	'tabrestore' => 'Возобновить шаблоны',
	'restoresubmitquestion' => 'Вы уверены, что хотите возобновить выбранные шаблоны? Действие не может быть отменено, Вы потеряете все изменение в шаблонах.',
	'titlerestoretemplates' => 'Возобновлены "%d" Шаблоны',
	'msgrestoretemplates' => 'Успешно возобновлены следующие шаблоны:',
	'desc_diagnostics' => '',
	'tabdiagnostics' => 'Диагностика',
	'desc_search' => '',
	'tabsearch' => 'Поиск Шаблонов',
	'tabplugins' => 'Плагины',
	'ls_module' => 'Плагины LoginShare',
	'wineditls' => 'Редактировать плагин LoginShare: %s',
	'tabsettings' => 'Настройки',
	'invalidloginshareplugin' => ' Неправильный плагин LoginShare, пожалуйста убедитесь в том, что плагин существует.',
	'lsnotitle' => 'Нет доступных настроек',
	'lsnomsg' => 'Нет доступных настроек для плагина LoginShare <b>"%s"</b>.',
	'loginsharefile' => 'LoginShare XML файл',
	'desc_loginsharefile' => 'Загрузить LoginShare XML файл',
	'titlenoelevatedls' => 'Невозможно импортировать LoginShare XML',
	'msgnoelevatedls' => SWIFT_PRODUCT.' не может импортировать файл LoginShare XML, так как Вам нужно зайти под пользователем, имеющим на это права.',
	'titlelsversioncheckfail' => 'Ошибка при проверке версии',
	'msglsversioncheckfail' => SWIFT_PRODUCT. ' не может импортировать плагин LoginShare,т.к. плагин был создан для более старой версии '.SWIFT_PRODUCT,
	'titlelsinvaliduniqueid' => 'Ошибка из-за дубликата уникального ID',
	'msglsinvaliduniqueid' => SWIFT_PRODUCT .' не может импортировать плагин LoginShare из-за конфликта уникального ID. Как правило это означает, что плагин уже присутсвует в системе.',
	'titlelsinvalidxml' => 'Неправильный файл XML',
	'msglsinvalidxml' => SWIFT_PRODUCT .' не может импортировать плагин LoginShare, т.к. файл XML поврежден, или имеет неизвестный формат.',
	'titlelsimported' => 'Импортирован плагин LoginShare',
	'msglsimported' => SWIFT_PRODUCT .' успешно испортировал плагин %s LoginShare.',
	'titlelsdeleted' => 'Удален плагин LoginShare',
	'msglsdeleted' => 'Успешно удален плагин "%s" LoginShare.',
	'groupusername' => 'Имя Пользователя',
	'desc_groupusername' => 'Введите имя пользователя для Группы Шаблонов. Нужно только, если выше активирована функция защиты паролем.',
	'isenabled' => 'Включено?',
	'desc_isenabled' => 'Управляйте использование этой группы путем включения/выключения этой функции.',
	'titlepwnomatch' => 'Неправильный пароль',
	'msgpwnomatch' => 'Пароли для выбранной группы не совпадают.',
	'titleinvalidgrouptitle' => 'Неправильное название Группы Шаблонов',
	'msginvalidgrouptitle' => 'В названии Группы Шаблонов допускаются только цыфры и буквы',
	'titlegrouptitleexists' => 'Неправильное название Группы Шаблонов',
	'msggrouptitleexists' => 'Существует Группа Шаблонов с таким же названием; пожалуйста выберите другое название.',
	'winedittemplategroup' => 'Редактировать Группу Шаблонов: %s',
	'tabpermissions' => 'Права',
	'titletgroupupdate' => 'Обновлена "%s" Группа Шаблонов',
	'msgtgroupupdate' => 'Успешно обновлена the "%s" Группа Шаблонов.',
	'titletgroupinsert' => 'Добавлена "%s" Группа Шаблонов',
	'msgtgroupinsert' => 'Успешно добавлена "%s" Группа Шаблонов.',
	'titletgroupnodel' => 'Невозмонжо удалить Группу(ы) Шаблонов',
	'msgtgroupnodel' => SWIFT_PRODUCT . ' невозможно удалить следующие Главные Группы Шаблонов:',
	'titletgroupdel' => 'Удалены "%d" Группы(а) Шаблонов',
	'msgtgroupdel' => 'Успешно удалены следующие Группы Шаблонов.',
	'titletgrouprestorecat' => 'Возобновленная Категория Группы Шаблонов',
	'msgtgrouprestorecat' => 'Успешно возобновлена "%s" категория  "%s" (%s) Группы Шаблонов',
	'titletgrouprestore' => 'Возобновлена(ы) "%d" Группа(ы) Шаблонов',
	'msgtgrouprestore' => 'Успешно возобновлена следующая  Группа Шаблонов.',
	'expandcontract' => 'Развернуть/Закрыть',
	'tgroupjump' => 'Группа Шаблонов: %s',
	'tabhistory' => 'История',
	'templateversion' => 'Версия Шаблона',
	'desc_templateversion' => '',
	'saveasnewversion' => 'Сохранить как Новую Группу',
	'titletemplaterestore' => 'Шаблон "%s" возобновлен',
	'msgtemplaterestore' => 'Успешно возобновлен Шаблон "%s" к начальным данным.',
	'titletemplateupdate' => 'Шаблон "%s" обновлен',
	'msgtemplateupdate' => 'Успешно обновлен Шаблон "%s"',
	'tabedittemplate' => 'Шаблон: %s (%s)',
	'titlenohistory' => 'Нет доступной Истории',
	'msgnohistory' => SWIFT_PRODUCT.' не местит в себе доступных записей истории шаблона "%s".',
	'historydescription' => 'Описание Истории',
	'historyitemlist' => '%s: %s (%s) Заметки: <i>%s</i>',
	'system' => '(Система)',
	'historyitemcurrent' => '%s: <i><b>Текущий</b></i> (%s)',
	'compare' => 'Сравнить',
	'current' => 'Текущий',
	'notcurrenttemp' => 'Старая Версия',
	'exportdiff' => 'Экспортировать в Diff (Уникальный формат)',
	'tabcomparison' => 'Сравнение',
	'changelognotes' => 'Заметки Журнала Изменений',
	'desc_changelognotes' => '',
	'none' => 'Никто',
	'inserttemplate' => 'Добавить шаблон',
	'inserttgroup' => 'Группа Шаблонов',
	'desc_inserttgroup' => 'Выберите Группу Шаблонов для даного Шаблона.',
	'restoreconfirmaskcat' => 'Вы уверены что хотите возобновить шаблоны в этой категории?\n Действие необратимо; возобновление приведет к потере всех измененных данных!',
	'inserttemplatetgroup' => 'Группа Шаблонов',
	'inserttemplatetcategory' => 'Категория Шаблона',
	'inserttemplatename' => 'Название Шаблона',
	'desc_inserttemplatename' => 'Введите Название Шаблона. Специальные символы запрещены.',
	'titleinserttemplatedupe' => 'Конфликт Названий Шаблонов',
	'msginserttemplatedupe' => 'Выберите другое имя для Шаблона, чтобы избежать конфликта с другим шаблонов этой Группы.',
	'titleinserttemplatechar' => 'Неправильное название шаблона',
	'msginserttemplatechar' => 'Пожалуйста, введить название шаблоны без специальных символов и пробелов.',
	'titleinserttemplate' => 'Добавлен шаблон "%s"',
	'msginserttemplate' => 'Успешно добавлен шаблон "%s" в  Группу шаблонов "%s"',
	'titletemplatedel' => 'Удаленный Шаблон',
	'msgtemplatedel' => 'Успешно удаленный шаблон "%s".',
	'titletemplateimportfailed' => 'Ошибка при Импортировании Шаблона',
	'msgtemplateimportfailed' => SWIFT_PRODUCT . ' ошибка при импорте шаблонов с пакета шаблонов %s. Пожалуйста, проверьте целосность файла.',
	'titlelsupdate' => 'LoginShare обновление',
	'msglsupdate' => 'Успешно обновлены настройки "%s" LoginShare плагина',
	'titletgroupmerge' => 'Группа Шаблонов "%s" успешна объединена с импортированным файлом',
	'msgtgroupmerge' => SWIFT_PRODUCT . ' объединила шаблоны из импортирована файла шаблонов "%s" в Группу Шаблонов "%s"',
	'titletgroupimport' => 'Импортирована Группа Шаблонов "%s"',
	'msgtgroupimport' => SWIFT_PRODUCT . ' импортировал шаблоны с файла Шаблонов "%s" в Группу Шаблонов "%s"',
	'tabsettings_tickets' => 'Настройки: Тикеты',
	'tabsettings_livechat' => 'Настройки: Онлайн Консультант',
	// ======= END v4 LOCALES =======

	'templates' => 'Templates',

	// ======= IMPORT/EXPORT =======
	'importexport' => 'Импорт/Экспорт',
	'exporttemplates' => 'Экспортировать Шаблоны',
	'exporttgroup' => 'Группа Шаблонов',
	'desc_exporttgroup' => 'Выберите Группу Шаблонов, в которую должны буть экспортированы шаблоны.',
	'exportxml' => 'Экпортировать XML',
	'filename' => 'Имя файла',
	'desc_filename' => 'Введите имя экспортируемого файла.',
	'exportoptions' => 'Опции экспорта',
	'desc_exportoptions' => 'Выберите опции экспорта. Если Вы выберете "Экспортировать только изменения," будут экспортированы только измененные файлы.',
	'exportalltemplates' => 'Экспортировать все Шаблоны',
	'exportmodifications' => 'Экспортировать только Изменения',
	'importtemplates' => 'Импортировать шаблоны',
	'templatefile' => 'XML файл Шаблона',
	'desc_templatefile' => 'Загрузите XML файл для импорта.',
	'createnewgroup' => '-- Создать группу шаблонов --',
	'mergewith' => 'Объединить с',
	'desc_mergewith' => 'Вы можете объединить изменения из импортирована файла с существующей Группой Шаблонов, или создать новую группу.',
	'ignoreversion' => 'Игнорировать Версии',
	'desc_ignoreversion' => 'Если выбрано, версия импортированого файла будет проигнорирована. Рекомендуется не включать данную опцию т.к. она может вызвать проблемы с отображением.',
	'importxml' => 'Импортировать XML',
	'tgroupmergeconfirm' => 'Группа шаблонов "%s" объединена с импортированным файлом',
	'versioncheckfailed' => 'Ошибка при проверке версии: Загруженный файл создан для старой версии '.SWIFT_PRODUCT,
	'tgroupnewimportconfirm' => 'Группа шаблонов "%s" успешно импортирована',

	// ======= INSERT GROUP =======
	'insertemplategroup' => 'Добавить Группу Шаблонов',
	'templategroupdetails' => 'Детали Группы Шаблонов',
	'tgrouptitle' => 'Название Группы Шаблонов',
	'desc_tgrouptitle' => 'Введите название Группы Шаблонов.',
	'companyname' => 'Название Компании',
	'desc_companyname' => 'Введите навзание компании для связки с Группой Шаблонов.',
	'generaloptions' => 'Общие Настройки',
	'defaultlanguage' => 'Язык по умолчанию',
	'desc_defaultlanguage' => 'Выберите язык по умолчанию для этой Группы Шаблонов. Клиенты смогут выбрать свой язык.',
	'usergroups' => 'Стандартные Группы Пользователей',
	'guestusergroup' => 'Группы Гостей',
	'desc_guestusergroup' => 'Выберите стандартную группу для гостей.',
	'regusergroup' => 'Группа Зарегистрированных пользователей',
	'desc_regusergroup' => 'Выберите Группу Зарегистрированых Пользователей.',
	'passwordprotection' => 'Защита Паролем',
	'enablepassword' => 'Включает Защиту паролем',
	'desc_enablepassword' => 'Управление защитой паролем для этой Группы пользователей. '.SWIFT_PRODUCT. ' использует HTTP аутентификацию если включена защита паролем.',
	'password' => 'Пароль',
	'desc_password' => 'Введите пароль для этой группы шаблонов. Нужно только если выбрана защита паролем.',
	'passwordconfirm' => 'Пароль (Подтверждение)',
	'desc_passwordconfirm' => 'Введите Пароль для подтверждения',
	'restrictgroups' => 'Ограничить Группу Пользователей',
	'desc_restrictgroups' => 'Если Включено, пользователи только выбранной группы зарегистрированных пользователей смогут зайти в Центр Поддержки для этой Группы Шаблонов.',
	'passworddontmatch' => 'ОШИБКА: пароли не совпадают',
	'invalidgrouptitle' => 'ОШИБКА: разрешены только буквы и цыфры в названии Группы Шаблонов',
	'copyfrom' => 'Скопировать шаблоны из',
	'desc_copyfrom' => 'Выберите группу шаблонов из которой '.SWIFT_PRODUCT.' скопирует Шаблоны.',
	'grouptitleexists' => 'ОШИБКА: неправильное Название Группы. Название использует другая группа шаблонов; пожалуйста, выберите другое название.',
	'promptticketpriority' => 'Запрашивать Приоритеты Тикетов?',
	'desc_promptticketpriority' => 'Если включено, Пользователю будет предложено выбрать приоритет во время создания тикета.',
	'prompttickettype' => 'Запрашивать Тип Тикетов?',
	'desc_prompttickettype' => 'Если включено, Пользователю будет предложено выбрать тип во время создания тикета.',
	'tickettype' => 'Стандартный тип тикета',
	'desc_tickettype' => 'Выберите стандартный тип тикета для этой Группы шаблонов.',
	'ticketstatus' => 'Стандартный статус тикета',
	'desc_ticketstatus' => 'Выберите стандартный статус тикета для этой Группы шаблонов.',
	'ticketpriority' => 'Стандартный приоритет тикета',
	'desc_ticketpriority' => 'Выберите стандартный приоритет тикета для этой Группы шаблонов.',
	'ticketdep' => 'Стандартное Подразделение',
	'desc_ticketdep' => 'Выберите Стандартное Подразделение.',
	'livechatdep' => 'Стандартное Подразделение',
	'desc_livechatdep' => 'Выберите Стандартное Подразделение.',
	'ticketsdeptitle' => '%s (Тикетов)',
	'livesupportdeptitle' => '%s (Онлайн Консультант)',
	'isdefault' => 'Является Стандартной Группой Шаблонов',
	'desc_isdefault' => '',
	'loginshare' => 'LoginShare модуль',
	'desc_loginshare' => 'Выберите модуль LoginShare для аутентификации посетителей этой Группы Шаблонов.',

	// ======= MANAGE TEMPLATE GROUPS =======
	'grouptitle' => 'Название Группы',
	'glanguage' => 'Язык',
	'managegroups' => 'Управление Группами',
	'templategroups' => 'Группы Шаблонов',
	'desc_templategroups' => '',
	'grouplist' => 'Список Групп',
	'restore' => 'Восстановить',
	'export' => 'Экспортировать XML',
	'groupinsertconfirm' => 'Группа Шаблонов "%s" успешно добавлена',
	'groupdelconfirm' => 'Группа Шаблонов "%s" успешно удалена',
	'restoreconfirmask' => 'Вы уверены что хотите возобновить группу шаблонов?\n Действие необратимо; воостановление приведет к потере всех отредактированных данных!',
	'restoreconfirm' => 'Группа Шаблонов "%s" воостановлена в Стандартные Шаблоны',
	'inserttemplategroup' => 'Добавить группу',
	'edittemplategroup' => 'Редактировать группу',
	'invalidgroup' => 'Неправльная Группа Шаблонов',
	'groupupdateconfirm' => 'Группа Шаблонов "%s" успешно обновлена',

	// ======= MANAGE TEMPLATES =======
	'desc_templates' => '',
	'managetemplates' => 'Управление Шаблонами',
	'templatetitle' => 'Шаблоны: %s',
	'templatecategories' => 'Категории Шаблонов',
	'expand' => 'Раскрыть',
	'groupjump' => 'Перейти в группу',
	'legend' => 'Легенда: ',
	'notmodified' => 'Не изменена',
	'modified' => 'Изменена',
	'upgrade' => 'Нужно обязательное воостановление',
	'expandall' => 'Раскрыть Все',
	'jump' => 'Перейти',
	'templategroup' => 'Группа Шаблонов',
	'desc_templategroup' => '',
	'invalidtemplate' => 'Неправильный Шаблон',
	'edittemplate' => 'Редактировать Шаблон',
	'edittemplatetitle' => 'Шаблон: %s (Группа: %s)',
	'generalinfo' => 'Общая информация',
	'templatedata' => 'Данные Шаблона',
	'savetemplate' => 'Сохранить',
	'saveandreload' => 'Сохранить &amp; Перезагрузить',
	'preview' => 'Предварительный просмотр',
	'restore' => 'Возобновить',
	'copyclipboard' => 'Копировать в буфер обмена',
	'templatestatus' => 'Статус',
	'desc_templatestatus' => '',
	'tstatus' => '<img src="%s" align="absmiddle" border="0" /> %s', // Switch position for RTL language
	'dateadded' => 'Дата Добавления/Изменения',
	'desc_dateadded' => '',
	'contents' => '',
	'desc_contents' => '',
	'templateupdateconfirm' => 'Шаблон "%s" успешно обновлены',
	'templaterestoreconfirm' => 'Шаблоны "%s" воостановлены к начальному состоянию',
	'templatesrestoreconfirm' => '%s Шаблоны воостановлены к начальному состоянию',
	'restoretemplates' => 'Воостановить Шаблоны',
	'clipboardconfirm' => 'Данные шаблоны были скопированы в буфер. Теперь Вы можете вставить эго в любой HTML редактор.',
	'clipboardconfirmmoz' => 'Выбран текст для копирования. Нажмите Ctrl+C чтобы скопировать текст.',

	// Diagnostics
	'diagnostics' => 'Диагностика',
	'listmodified' => 'Последние измененные Шаблоны',
	'listtorestore' => 'Список Шаблонов на Воостановление',
	'moditgroup' => 'Группа Шаблонов',
	'desc_moditgroup' => '',
	'list' => 'Список',
	'diagnosesmarty' => 'Диагностировать на ошибки в Шаблоне',
	'diagtgroup' => 'Группа Шаблонов',
	'desc_diagtgroup' => '',
	'diagnose' => 'Диагностика',
	'modifiedtemplates' => 'Измененные шаблоны (Группа: %s)',
	'listtemplates' => 'Список Шаблонов (Группа: %s)',
	'templatename' => 'Название Шаблона',
	'status' => 'Статус',
	'diagnoseerrors' => 'Определить Ошибки (Группа: %s)',
	'compiletime' => 'Время компиляции',

	// Search
	'search' => 'Поиск',
	'searchtemplates' => 'Поиск Шаблонов',
	'query' => 'Очередь Поиска',
	'desc_query' => 'Введите текст для поиск',
	'searchtgroup' => 'Искать В',
	'desc_searchtgroup' => 'Выберите Группу шаблонов для поиска',
	'searchqueryd' => 'Очередь Поиска: %s',

	// LoginShare
	'loginshare' => 'LoginShare',
	'ls_module' => 'LoginShare плагин',
	'pluginlist' => 'Список Плагинов',
	'hostname' => 'Имя хоста',
	'dbname' => 'DB Name',
	'dbuser' => 'DB User',
	'dbpass' => 'DB Password',
	'tableprefix' => 'Префик таблицы',
	'ldaphostname' => 'Active Directory Host',
	'ldapport' => 'Port (Default: 389)',
	'ldapbasedn' => 'Base DN',
	'ldaprdn' => 'RDN',
	'ldappassword' => 'Пароль',

	// H-Sphere
	'hsphostserver' => 'Server Hostname',
	'hspport' => 'Server Port',
	'hspurl' => 'XML API URL',
	'hspconnectfail' => 'Невозможно соединится с сервером. Попробуйте позже.',

	// ======= Category List =======
	'template_general' => 'Общее',
	'template_chat' => 'Онлайн Консультант',
	'template_troubleshooter' => 'Устранение неполадок',
	'template_news' => 'Новости',
	'template_downloads' => 'Загрузки',
	'template_knowledgebase' => 'База Знаний',
	'template_tickets' => 'Тикеты',
	'template_parser' => 'Парсер Писем',
	'template_purchase' => 'Покупатель Тикетов',

	// ======= LOGINSHARE =======
	'loginapi_modernbill' => 'ModernBill',
	'loginapi_ipb' => 'Invision Power Board',
	'loginapi_vb' => 'vBulletin',
	'loginapi_osc' => 'osCommerce',
	'loginapi_iono' => 'IONO License Manager',
	'loginapi_plexum' => 'Plexum',
	'loginapi_awbs' => 'AWBS',
	'loginapi_phpaudit' => 'PHPAudit v2',
	'loginapi_whmautopilot' => 'WHMAP v3',
	'loginapi_activedirectory' => 'Active Directory/LDAP',
	'loginapi_activedirectoryssl' => 'Active Directory/LDAP (SSL)',
	'loginapi_ticketpurchaser' => 'Ticker Purchaser',
	'loginapi_xcart' => 'X-Cart',
	'loginapi_phpbb' => 'PHPBB',
	'loginapi_smf' => 'Simple Machines Forum',
	'loginapi_mybb' => 'MyBB',
	'loginapi_xmb' => 'XMB',
	'loginapi_clientexec' => 'Clientexec',
	'loginapi_joomla' => 'Joomla CMS',
	'loginapi_hsphere' => 'H-Sphere XML-API',
	'loginapi_phpprobid' => 'PHPProBid',
	'loginapi_cubecart' => 'CubeCart',
	'loginapi_modernbillv5' => 'ModernBill v5',
	'loginapi_cscart' => 'CS-Cart',
	'loginapi_fsr' => 'FSRevolution',
	'loginapi_viper' => 'Viper Cart',
	'loginapi_xoops' => 'XOOPS',
	'loginapi_whmcsintegration' => 'WHMCS - Integration Placeholder Only (Not for direct logins)',
);

?>