<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'actionvariables' => 'Переменные',
	'livechat' => 'Чат',
	'rules' => 'Правила',
	'insertgroup' => 'Вставить группы',
	'editgroup' => 'Изменить группу',
	'insertban' => 'Вставить Бан',
	'editban' => 'Изменить Бан',
	'actionvisitorexperience' => 'Опыт посетителя',
	'actionstaffalerts' => 'Персонал предупреждений',
	'hexcode' => 'Шестнадцатиричный цветной код',
	'wineditgroup' => 'Изменить группу посетителей: %s',
	'visitorgroups' => 'Группы посетителя',
	'titlenorulecriteria' => 'Нет указанных критериев',
	'msgnorulecriteria' => SWIFT_PRODUCT . ' Не в состоянии вставить правило посетителя так как критерии не были указаны.',
	'titlenoruleactions' => 'Нет указанных действий',
	'msgnoruleactions' => SWIFT_PRODUCT . ' Не в состоянии вставить правило посетителя, так как никакие действия не были указаны.',
	'invalidgroup' => 'Неверно указанная группа. Убедитесь, что группа посетителей существует в базе данных и база данных не испорчена',
	'visitorgrouptitle' => 'Заглавие группы посетителей',
	'desc_visitorgrouptitle' => 'Конкретизируйте заглавие группы посетителей.',
	'groupcolor' => 'Цвет группы',
	'desc_groupcolor' => 'Конкретизируйте цвет для этой группы\ 'S' заглавия, которое будет показано на решетке посетителя.',
	'lastupdate' => 'Последнее обновление',
	'titledelvisitorgroup' => 'Удаленная "%d" группа(s) посетителей',
	'msgdelvisitorgroup' => 'Успешно удалены следующие группы посетителей из базы данных:',
	'titleinsertgroup' => 'Добавлена группа посетителей "% S"',
	'msginsertgroup' => 'Успешно выведен посетитель группы "<font% color="%s"> S </ FONT>" в базе данных.',
	'titleupdategroup' => 'Обновленная Группа Посетителей "%s"',
	'msgupdategroup' => 'Успешно обновленна группа посетителей "<font color="%s">%s</font>".',
	'isregex' => 'Это регулярное выражение?',
	'desc_isregex' => 'Если включено, '.SWIFT_PRODUCT.' сравнить посетители IP, используя регулярное выражение, указанное выше.',
	'titleinsertban' => 'Вставленный Бан',
	'msginsertban' => 'Успешно вставленный Бан "%s" в базе данных.',
	'titleupdateban' => 'Обновленный Бан',
	'msgupdateban' => 'Успешно обновленный Бан "%s"',
	'wineditban' => 'Редактируйте Бан: %s',
	'gridisregex' => 'RegEx?',
	'titledelbans' => 'Удаленный "%d" Бан(s) Посетителя',
	'msgdelbans' => 'Баны для посетителей были успешно удалены с базы данных',
	'onlinestatus' => 'Онлайн Статус',
	'desc_onlinestatus' => '',
	'disconnect' => 'Отключить',
	'logintime' => 'Логин',
	'lastactivity' => 'Последняя активность',
	'username' => 'Имя пользователя',
	'fullname' => 'Полное имя',
	'titledcstaff' => 'Разъединенные "%d" зарегистрированые пользователи персонала',
	'msgdcstaff' => 'Успешно отключены следующие пользователи сотрудников из системы:',
	'skills' => 'Навыки',
	'desc_skills' => '',
	'skilltitle' => 'Заглавие навыка',
	'alertemail' => 'Оповещение Е-мейл',
	'wineditskill' => 'Изменить навык: %s',
	'messagerouting' => 'Маршрутизация сообщений',
	'desc_messagerouting' => '',
	'mrdepartment' => 'Подразделение',
	'mraction' => 'Действие',
	'titleupdmr' => 'Обновленные правила маршрутизации сообщений',
	'msgupdmr' => 'Успешно обновленные правила маршрутизации сообщений, детали внесено ниже в список:',
	'routetotickets' => 'Направлять билетом',
	'mrdepartment' => 'Подразделение',
	'routetoemail' => 'Направлять Е-мейлом',
	'mremail' => 'Е-мейл (s)',
	'insertrule' => 'Вставить правило',
	'desc_insertrule' => '',
	'insertcriteria' => 'Вставить критерии',
	'tabactions' => 'Действия',
	'insertaction' => 'Вставить действия',
	'ruletitle' => 'Заглавие правила',
	'desc_ruletitle' => 'Ввести заглавие правила',
	'rulestop' => 'Перестать обработывать правила',
	'desc_rulestop' => 'Если включены, другие правила они не будут обработаны',
	'sortorder' => 'Сортировка',
	'desc_sortorder' => 'Указать порядок сортировки для этого правила. Правила всегда обрабатываются в порядке возрастания.',
	'criteria' => 'Критерии',
	'smatchall' => 'Искать все (AND)',
	'smatchany' => 'Искать любое (OR)',
	'matchtype' => 'Выбор критериев',
	'smatchtype' => 'Тип соответствия',
	'desc_matchtype' => 'Выберите метод группировки по критериям полей.',
	'clearall' => 'Очистить все',
	'titlevrcoreerror' => 'Основные ошибки: неудачная вставка',
	'msgvrcoreerror' => 'Невозможно вставить правило посетителя',
	'invalidvisitorrule' => 'ОШИБКА: Неверное правило посетителя, убедитесь, что правило посетителя существует в базе данных ',
	'editrule' => 'Изменить правила',
	'desc_editrule' => '',
	'if' => 'Если',
	'titleinsertrule' => 'Включено правило посетителя "% S"',
	'msginsertrule' => 'Успешно выведено правило посетителя "% S" в базе данных.',
	'actaddvariable' => '<b>Переменный:</b> %s = %s',
	'actvisitorexperience' => '<b> Опыт посетителя:</b> %s',
	'actstaffalert' => '<b>Staff Тревога:</b> Название: %s, Соотношение: %s',
	'actsetskill' => '<b>Set Навыки:</b> Навыки названия: %s',
	'actsetgroup' => '<b>Установите Группу:</b> Посетитель Группа Название: %s',
	'actsetdepartment' => '<b>Установить подразделение :</b> Название подраздиления: %s',
	'actsetcolor' => '<b>Установить цвет:</b> Цветной код: %s',
	'actbanvisitor' => '<b>Бан посетителя:</b> Тип: %s',
	'titleupdaterule' => 'Обновленное Правило Посетителя "%s"',
	'msgupdaterule' => 'Успешно обновленное правило посетителя "%s".',
	'titledelvrules' => 'Удалено "%s" Правило посетителя(s)',
	'msgdelvrules' => 'Успешно удалено следующее правило посетителя(s).<br>%s',
	'settings' => 'Настройки',
	'lssettings' => 'Настройки',
	'desc_lssettings' => '',
	'tabsettings' => 'Настройки',
	'insertskill' => 'Вставьте навык',
	'desc_insertskill' => '',
	'tabassignments' => 'Задания',
	'skilltitle' => 'Заглавие навыка',
	'desc_skilltitle' => 'Введите заглавие навыка',
	'skilldesc' => 'Описание навыка',
	'desc_skilldesc' => 'Введите навык описание. Максимально допкскается 255 символо.',
	'skillemail' => 'Е-мейл',
	'desc_skillemail' => 'Введите адрес электронной почты группы навыков',
	'skillsperm' => 'Задание работника',
	'ruletype' => 'Правило триггера',
	'desc_ruletype' => 'Выберите действие, когда правило срабатывает',
	'ruletype_1' => 'Когда чат устанавливается',
	'ruletype_2' => 'Когда посетитель открывает страницу',
	'ruletype_3' => 'Когда посетитель открывает сайт',
	'ruletype_4' => 'Когда посетитель добавлен в очередь на чат',
	'actionsetskill' => 'Набор навыков',
	'actionsetdepartment' => 'Установить подразделение',
	'actionsetgroup' => 'Установить группу',
	'actionsetcolor' => 'Установить цвет',
	'actionbanvisitor' => 'Бан посетителя',
	'notavailable' => '-- Не доступный --',
	'inlinechat' => 'Встроенный чат',
	'engagevisitor' => 'Привлечение посетителей',
	'customengagevisitor' => 'Привлечение посетителей (Custom)',
	'editskill' => 'Изменить навык',
	'invalidchatskill' => 'Неверный навык чата. Пожалуйста, убедитесь, что навыки чата существуют в базе данных.',
	'titledelchatskills' => 'Удалить "%d" Навыки чата (s)',
	'msgdelchatskills' => 'Успешно удалены следующие навыки чата (s) из базы данных:<br />%s',
	'titleinsertskill' => 'Добавлены навыки чата',
	'msginsertskill' => 'Успешно выведен "%s" навык чата из базы даных.',
	'titleupdateskill' => 'Обновлено навык чата',
	'msgupdateskill' => 'Успешно обновлен "%s" навык чата.',
	'preservemessage' => 'Сохраните запись сообщения',
	'seperatevia' => 'розделить через ;',

	// ======= RULE STRINGS =======
	'rule_currentpage' => 'Просмотр - Текущая страница',
	'desc_rule_currentpage' => 'В настоящее время посетитель просматривает активную страницу',
	'rule_currentpageurl' => 'Посетитель - Текущая страница (URL)',
	'desc_rule_currentpageurl' => 'В настоящее время посетитель просматривает активную страницу ',
	'rule_currentpagetitle' => 'Посетитель - Текущая страница (Название)',
	'desc_rule_currentpagetitle' => 'В настоящее время посетитель просматривает активную страницу',
	'rule_numberofpages' => 'Просмотр - количество страниц',
	'desc_rule_numberofpages' => 'Количество страниц посетитель открыл в активной сессии',
	'rule_previouspagetitle' => 'Просмотр - предыдущую страницу (Название)',
	'desc_rule_previouspagetitle' => 'Посетитель открыл активную страницу ранее',
	'rule_previouspageurl' => 'Просмотр - предыдущую страницу (URL)',
	'desc_rule_previouspageurl' => 'Посетитель открыл активную страницу ранее',
	'rule_referringurl' => 'Просмотр - URL ссылки',
	'desc_rule_referringurl' => 'Ссылка URL активной страницы',
	'rule_searchenginefound' => 'Просмотр - Найденный поисковик',
	'desc_rule_searchenginefound' => 'Логическое свойство, в зависимости от того перешел ли посетитель с поисковых систем',
	'rule_searchenginename' => 'Просмотр - Имя Поисковика',
	'desc_rule_searchenginename' => 'Поисковик, от которого посетитель был направлен',
	'rule_searchenginequery' => 'Browsing - Строка запроса поисковика',
	'desc_rule_searchenginequery' => 'Запрос поисковой строке, которая была использована для поиска',
	'rule_visitedpagetitle' => 'Просмотр - Посещенные страницы (Название)',
	'desc_rule_visitedpagetitle' => 'Все страницы посетитель посетил в активной сессии',
	'rule_visitedpageurl' => 'Просмотр - Посещенных страниц (URL)',
	'desc_rule_visitedpageurl' => 'Все страницы посетитель посетил в активной сессии',
	'rule_repeatvisit' => 'Посетитель - Повторный Визит',
	'desc_rule_repeatvisit' => 'Является повторным или новым посетителем',
	'rule_browser' => 'Посетитель - Браузер',
	'desc_rule_browser' => 'Браузер, используемый посетителем. Пример: Safari, Mozilla, Internet Explorer',
	'rule_ipaddress' => 'Посетитель - IP-адрес',
	'desc_rule_ipaddress' => 'IP-адрес посетителя',
	'rule_onlinestaff' => 'Работник - Интернет работник',
	'desc_rule_onlinestaff' => 'Собственность основывается на штате сотрудников, которые находятся онлайн ',
	'rule_onlinestaffskills' => 'Работник - Интернет работник с навыками',
	'desc_rule_onlinestaffskills' => 'Свойство, основанное на он-лайн работнике с указанными навыками',
	'rule_onlinestaffdepartments' => 'Работник - Он-лайн Работник, работающий в подразделении',
	'desc_rule_onlinestaffdepartments' => 'Свойство, основанно на состоянии онлайн работника, работающего в определенном отделе',
	'rule_timeinsite' => 'Время - время в сайте',
	'desc_rule_timeinsite' => 'Общее время, проведенное на сайте',
	'rule_timeinchat' => 'Время - время в чате',
	'desc_rule_timeinchat' => 'Общее время, проведенное в активном чате',
	'rule_timeagententry' => 'Время - Секунды, с последнего визита Работника',
	'desc_rule_timeagententry' => 'Количество секунд, с последнего сообщения Работника',
	'rule_timevisitorentry' => 'Time - Секунды, с последней записи посетителя',
	'desc_rule_timevisitorentry' => 'Количество секунд, с последнего сообщения посетителя',
	'rule_timeagentvisitorentry' => 'Время - секунды после последнего Работника или вход посетителя',
	'desc_timeagentvisitorentry' => 'Количество секунд,  с последнего Работника и  сообщения посетителя',
	'rule_chatagentlastmessage' => 'Чат - Последнее сообщение Работника',
	'desc_rule_chatagentlastmessage' => 'Содержание последнего сообщения Работника',
	'rule_chatvisitorlastmessage' => 'Чат - Последнее сообщение Работника',
	'desc_rule_chatvisitorlastmessage' => 'Содержание последнего сообщения посетителя',
	'rule_chatwithagentmessage' => 'Чат - чат с сообщением Работника',
	'desc_rule_chatwithagentmessage' => 'Логически, если есть сообщения Работника в Чате',
	'rule_chatwithvisitormessage' => 'Чат - чат с сообщением посетителя',
	'desc_rule_chatwithvisitormessage' => 'Логически, если есть сообщения Работника в Чате',
	'rule_chatwithagentvisitormessage' => 'Чат - чат с сообщением посетителя',
	'desc_rule_chatwithagentvisitormessage' => 'Логически, если есть сообщения Работника или Посетителя в Чате',
	'rule_chatinchat' => 'Чат - в чате',
	'desc_rule_chatinchat' => 'Логически, если есть чат был принят Работникои пользоватилем',
	'rule_chatrefusedchat' => 'Чат - откланенный Чат',
	'desc_rule_chatrefusedchat' => 'Логически, если есть чат был отклонен Работникои пользоватилем',
	'rule_geocountry' => 'IP - Страна',
	'desc_rule_geocountry' => '',
	'rule_geocity' => 'IP - Город',
	'desc_rule_geocity' => '',
	'rule_geoipregion' => 'IP - Регион',
	'desc_rule_geoipregion' => '',
	'rule_geoorganization' => 'IP - Организация',
	'desc_rule_geoorganization' => '',
	'rule_geotimezone' => 'IP - Время зоны',
	'desc_rule_geotimezone' => '',
	'rule_geoisp' => 'IP - Провайдер',
	'desc_rule_geoisp' => '',
	'rule_geoconnectiontype' => 'IP - Скорость Интернета',
	'desc_rule_geoconnectiontype' => '',
	'rule_geoippostalcode' => 'IP - Почтовый индекс',
	'desc_rule_geoippostalcode' => '',
	'rule_geoipmetrocode' => 'IP - Код Метро',
	'desc_rule_geoipmetrocode' => '',
	'rule_geoipareacode' => 'IP - Код зоны',
	'desc_rule_geoipareacode' => '',
	'rule_geoiplatitude' => 'IP - Широта',
	'desc_rule_geoiplatitude' => '',
	'rule_geoiplongitude' => 'IP - Долгота',
	'desc_rule_geoiplongitude' => '',
	// ======= END v4 LOCALES =======


	'livesupport' => 'Он-лайн консультант',
	'visitorbans' => 'Забаненый посетитель',
	'desc_visitorbans' => 'Забаненый посетитель по IP адресу. Забаненый посетитель может быть добавлен изнутри LiveResponse Desktop Application. Забаненый посетитель не будет появляться в отслеживании посетителей и не будет в состоянии видеть статус он-лайн консультанта, кнопку в интерфейсе поддержки клиентов.',
	'visitorbanlist' => 'Забаненый список Посетителя',
	'ipaddress' => 'IP Адрес',
	'desc_ipaddress' => 'Ввести IP адрес Бана.',
	'addedby' => 'Добавил',
	'bandate' => 'Дата создания',
	'insertvisitorban' => 'Вставить Бан Посетителя',
	'invalidip' => 'ОШИБКА: Неверный IP-адрес',
	'ipinsertconfirm' => 'Забаненый Посетитель по IP-адресу "%s" вставленый успешно',
	'ipupdateconfirm' => 'Забаненый Посетитель обновлен для IP-адреса "%s"',
	'ipdelconfirm' => 'Забаненый Посетитель успешно удален',
	'invalidban' => 'Неправильная запись Забаненого Посетителя',
	'updatevisitorban' => 'Забаненый Посетитель обновлен',
);
?>