<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN v4 LOCALES =======
	'lrskills' => 'Навыки',
	'lrrules' => 'Правила Посетителей',
	'lrgroups' => 'Группы Посетителей',
	'lrbans' => 'Баны Посетителей',
	'lrmessagerouting' => 'Сообщение Маршрутизации',
	'corestaff' => 'Персонал',
	'coreteams' => 'Команды',
	'admin_tmpcanpersonalize' => 'Имеет доступ к Шаблоны > Настроить',
	'coreloginshare' => 'LoginShare Персонала',
	'coredepartments' => 'Подраделения',
	'coretemplategroups' => 'Группы Шаблонов',
	'coretemplates' => 'Шаблоны',
	'coreusergroups' => 'Группы Пользователей',
	'staff_profile' => 'Может изменять Профиль',
	'staff_changepassword' => 'Может изменять Пароль',
	'coretemplateloginshare' => 'LoginShare Пользователя',
	'corecustomfieldgroups' => 'Персональные Группы Полей',
	'corecustomfields' => 'Свои Поля',
	'staff_newssubscribers' => 'Подписчики Новостей',
	'staff_newscategories' => 'Категории Новостей',
	'staff_newscanpublicinsert' => 'Может добавлять Публичные Новости',
	'staff_newsitems' => 'Новости',
	'staff_troubleshootercategories' => 'Категории',
	'corewidgets' => 'Виджеты',
	'corelanguages' => 'Языки',
	'staff_comments' => 'Комментарии',
	'corelanguagephrases' => 'Фразы Языков',
	'livechatcalls' => 'Звонки',
	'parserqueues' => 'Очереди Писем',
	'admin_tcanrunmoveattachments' => 'Может перемещать Вложения',
	'staff_troubleshootersteps' => 'Шаги',
	'parserlogs' => 'Логи Парсера',
	'parserrules' => 'Правила Парсера',
	'parserbreaklines' => 'Линии Обрыва',
	'parserbans' => 'Баны',
	'parsercatchall' => 'Правила Сбора всего',
	'admin_canrunimport' => 'Может запускать Импортирование',
	'parserblockages' => 'Блокировки Цыклов',
	'parserlooprule' => 'Правила Цыклов',
	'issuestatus' => 'Статусы',
	'issuepriorities' => 'Приоритеты',
	'issueresolutions' => 'Решения',
	'issuelinks' => 'Связи',
	'issuetypes' => 'Типы',
	'ticketworkflows' => 'Рабочие процессы',
	'ticketstatuses' => 'Статусы',
	'ticketpriorities' => 'Приоритеты',
	'ticketfiletypes' => 'Типы Файлов',
	'staff_notifications' => 'Уведомления',
	'tickettypes' => 'Типы Тикетов',
	'ticketlinks' => 'Связи',
	'ticketbayes' => 'Bayesian Категории',
	'ticketslaplans' => 'SLA Планы',
	'ticketslaschedules' => 'SLA Расписания',
	'staff_ticketbilling' => 'Оплата Тикетов',
	'staff_tcanforward' => 'Может Переадресовывать Тикет',
	'staff_tcanreply' => 'Может Отвечать на Тикет',
	'staff_tcanfollowup' => 'Может создавать Присмотр',
	'staff_tcanrelease' => 'Может выпускать Тикет',
	'staff_ticketfollowup' => 'Присмотры',
	'staff_tcanviewauditlog' => 'Может смотреть журнал Проверок',
	'staff_ticketnotes' => 'Заметки Тикета',
	'staff_tcanworkflow' => 'Может Смотреть/Изменять Рабочие Процессы',
	'staff_tcansaveasdraft' => 'Может сохранять как Черновик',
	'staff_tcanbenchmarks' => 'Может смотреть Рейтинги',
	'ticketslaholidays' => 'SLA праздники',
	'ticketescalations' => 'Обострения',
	'corebenchmarks' => 'Рейтинги',
	'corescheduledtasks' => 'Запланированые Задания',
	'staff_usernotes' => 'Заметки Пользователя',
	'livechatnotes' => 'Заметки Чата',
	'livechatmessages' => 'Сообщения/Осмотры',
	'livechatcanned' => 'Заготовленые',
	'livechathistory' => 'История Чата',
	'winapplrbans' => 'Winapp: Баны Посетителей',
	'staff_kbcategories' => 'Категории',
	'staff_kbarticles' => 'Статьи',
	'staff_kbcaninsertpublishedarticles' => 'Может Публиковать Статьи',
	'staff_trcaninsertpublishedsteps' => 'Может Публиковать Шаги',
	'staff_tags' => 'Теги',
	'staff_tcansearch' => 'Может искать Тикеты',
	'staff_ticketmacros' => 'Макрос',
	'staff_ticketfilters' => 'Фильтра',
	'staff_ticketviews' => 'Просмотры',
	'staff_tickets' => 'Тикеты',
	'staff_ticketposts' => 'Сообщения Тикетов',
	'staff_tcanmarkasspam' => 'Может отмечать Тикет как Спам?',
	'staff_tcantrashticket' => 'Может перемещать тикет в Корзину?',
	'ls_canobserve' => 'Winapp: Может наблюдать за Чатами',
	'admin_canmanagetaggenerator' => 'Может управлять Генератором Тегов',
	'admin_canmanagerestapi' => 'Может управлять REST API',
	'admin_canviewloginlog' => 'Может смотреть Логи Входа',
	'admin_canviewactivitylog' => 'Может смотреть Логи Активности',
	'admin_canviewerrorlog' => 'Может смотреть Логи Ошибок',
	'admin_canviewdatabase' => 'Может смотреть Детали Базы данных',
	'admin_canrundiagnostics' => 'Может запускать диагностику',
	'admin_canviewdepartments' => 'Может смотреть Подразделения',
	'admin_lrcandeletevisitorgroup' => 'Может удалять Группы Посетителей',
	'admin_lrcaninsertvisitorgroup' => 'Может добавлять Группы Посетителей',
	'admin_lrcanupdatevisitorgroup' => 'Может обновлять Группы Посетителей',
	'admin_lrcanviewvisitorgroups' => 'Может смотреть Группы Посетителей',
	'admin_caninsertstaff' => 'Может добавлять Работников',
	'admin_caneditstaff' => 'Может обновлять Работников',
	'admin_candeletestaff' => 'Может удалять Работников',
	'admin_caninsertteams' => 'Может добавлять Команды',
	'admin_caneditteams' => 'Может обновлять Команды',
	'admin_candeleteteams' => 'Может удалять Команды',
	'admin_caninsertdepartment' => 'Может добавлять Подразделения',
	'admin_caneditdepartment' => 'Может редактировать Подразделения',
	'admin_candeletedepartment' => 'Может удалять Подразделения',
	'admin_canupdatesettings' => 'Может Обновлять Настройки',
	'admin_canrebuildgeoip' => 'Может Воостанавливать Базу IP',
	'admin_caninsertcfgroup' => 'Может добавлять свои Группы Полей',
	'admin_canupdatecfgroup' => 'Может обновлять свои Группы Полей',
	'admin_candeletecfgroup' => 'Может удалять свои Группы Полей',
	'admin_caninsertcustomfield' => 'Может добавлять Свои Поля',
	'admin_canupdatecustomfield' => 'Может обновлять Свои Поля',
	'admin_candeletecustomfield' => 'Может удалять Свои Поля',
	'admin_canviewlanguages' => 'Может смотреть Языки',
	'admin_caninsertlanguage' => 'Может добавлять Языки',
	'admin_canupdatelanguage' => 'Может обновлять Языки',
	'admin_candeletelanguage' => 'Может удалять Языки',
	'admin_canrestorelanguage' => 'Может воостанавливать Языки',
	'admin_canviewphrases' => 'Может смотреть Выражения',
	'admin_caninsertphrase' => 'Может добавлять Выражения',
	'admin_canupdatephrase' => 'Может обновлять Выражения',
	'admin_candeletephrase' => 'Может удалять Выражения',
	'admin_canimportphrases' => 'Может импортировать Языковый Пакет',
	'admin_canexportphrases' => 'Может экспортировать Языковый Пакет',
	'admin_canrestorephrases' => 'Может воостанавливать Выражения',
	'admin_canrunlanguagediagnostics' => 'Может запускать Дигностику Языков',
	'mod_ringroute' => 'RingRoute',
	'admin_canupdaterrprofiles' => 'Может обновлять Профили RingRoute',
	'admin_lrcanviewonlinestaff' => 'Может смотреть онлайн Персонал',
	'admin_lrcandisconnectstaff' => 'Может отключать онлайн Персонал',
	'admin_lrcanupdaterouting' => 'Может обновлять Правила Маршрутизации Сообщений',
	'admin_lrcanviewrouting' => 'Может смотреть Правила Маршрутизации Сообщений',
	'admin_lrcanviewbans' => 'Может смотреть баны по IP',
	'admin_lrcaninsertban' => 'Может добавлять баны по IP',
	'admin_lrcanupdateban' => 'Может обновлять баны по IP',
	'admin_lrcandeleteban' => 'Может удалять баны по IP',
	'admin_lrcanviewrules' => 'Может смотреть Правила Посетителей',
	'admin_lrcaninsertrule' => 'Может добавлять Правила Посетителей',
	'admin_lrcanupdaterule' => 'Может обновлять Правила Посетителей',
	'admin_lrcandeleterule' => 'Может удалять Правила Посетителей',
	'admin_lrcanviewskills' => 'Может смотреть Навыки',
	'admin_lrcaninsertskill' => 'Может добавлять Навыки',
	'admin_lrcanupdateskill' => 'Может обновлять Навыки',
	'admin_lrcandeleteskill' => 'Может удалять Навыки',
	'admin_mpcaninsertqueue' => 'Может добавлять очередь Email',
	'admin_mpcanupdatequeue' => 'Может обновлять очередь Email',
	'admin_mpcandeletequeue' => 'Может удалять очередь Email',
	'admin_mpcanviewqueues' => 'Может смотреть очередь Email',
	'admin_mpcanviewparserlogs' => 'Может смотреть Логи Парсера',
	'admin_mpcandeleteparserlogs' => 'Может удалять Логи Парсера',
	'mod_parser' => 'Парсер Почты',
	'admin_mpcaninsertrule' => 'Может Добавлять Правила',
	'admin_mpcanupdaterule' => 'Может Обновлять Правила',
	'admin_mpcandeleterule' => 'Может Удалять Правила',
	'admin_mpcanviewrules' => 'Может Смотреть Правила',
	'admin_mpcaninsertbreakline' => 'Может Добавлять Границы',
	'admin_mpcanupdatebreakline' => 'Может Обновлять Границы',
	'admin_mpcandeletebreaklines' => 'Может удалять Границы',
	'admin_mpcanviewbreaklines' => 'Может смотреть Границы',
	'admin_mpcaninsertban' => 'Может Добавлять Email Бан',
	'admin_mpcanupdateban' => 'Может обновлять Email Бан',
	'admin_mpcandeletebans' => 'Может удалять Email Бан',
	'admin_mpcanviewbans' => 'Может смотреть Email Бан',
	'admin_mpcaninsertcatchall' => 'Может добавлять Правило Сбора',
	'admin_mpcanupdatecatchall' => 'Может обновлять Правило Сбора',
	'admin_candeletecatchall' => 'Может удалять Правило Сбора',
	'admin_canviewcatchall' => 'Может смотреть Правило Сбора',
	'admin_iscanviewstatus' => 'Может смотреть Статус',
	'admin_iscaninsertstatus' => 'Может смотреть Статус',
	'admin_iscanupdatestatus' => 'Может добавлять Статус',
	'admin_iscandeletestatus' => 'Может удалять Статус',
	'admin_iscanviewpriorities' => 'Может смотреть Приоритеты',
	'admin_iscaninsertpriority' => 'Может добавлять Приоритеты',
	'admin_iscanupdatepriority' => 'Может обновлять Приоритеты',
	'admin_iscandeletepriorities' => 'Может удалять Приоритеты',
	'admin_iscanviewresolutions' => 'Может смотреть Решения',
	'admin_iscaninsertresolution' => 'Может добавлять Решения',
	'admin_iscanupdateresolution' => 'Может обновлять Решения',
	'admin_iscandeleteresolutions' => 'Может удалять Решения',
	'admin_iscanviewlinks' => 'Может смотреть Связи',
	'admin_iscaninsertlink' => 'Может добавлять Связи',
	'admin_iscanupdatelink' => 'Может обновлять Связи',
	'admin_iscandeletelinks' => 'Может удалять Связи',
	'admin_iscanviewtypes' => 'Может смотреть Типы',
	'admin_iscaninsertype' => 'Может добавлять Типы',
	'admin_iscanupdatetype' => 'Может обновлять Типы',
	'admin_iscandeletetypes' => 'Может удалять Типы',
	'mod_issues' => 'Вопросы',
	'mod_tickets' => 'Тикеты',
	'admin_tcanviewbayescategories' => 'Может смотреть категории Bayesian',
	'admin_tcandeletebayescategories' => 'Может удалять категории Bayesian',
	'admin_tcaninsertbayescategory' => 'Может добавлять категории Bayesian',
	'admin_tcanupdatebayescategory' => 'Может обновлять категории Bayesian',
	'admin_tcanrunbayesdiagnostics' => 'Может запускать диагностику Bayesian',
	'admin_tcanviewslaplans' => 'Может смотреть SLA планы',
	'admin_tcaninsertslaplan' => 'Может добавлять SLA планы',
	'admin_tcanupdateslaplan' => 'Может обновлять SLA планы',
	'admin_tcandeleteslaplans' => 'Может удалять SLA планы',
	'admin_tcanviewslaschedules' => 'Может смотреть SLA расписания',
	'admin_tcaninsertslaschedules' => 'Может добавлять SLA расписания',
	'admin_tcanupdateslaschedules' => 'Может обновлять SLA расписания',
	'admin_tcandeleteslaschedules' => 'Может удалять SLA расписания',
	'admin_tcanviewslaholidays' => 'Может смотреть SLA Праздники',
	'admin_tcaninsertslaholidays' => 'Может добавлять SLA Праздники',
	'admin_tcanupdateslaholidays' => 'Может обновлять SLA Праздники',
	'admin_tcandeleteslaholidays' => 'Может удалять SLA Праздники',
	'admin_tcanimpexslaholidays' => 'Может Импортировать/Экспортировать SLA Праздники',
	'admin_tcanviewescalations' => 'Может смотреть Правила Обострения',
	'admin_tcaninsertescalations' => 'Может добавлять Правила Обострения',
	'admin_tcanupdateescalations' => 'Может обновлять Правила Обострения',
	'admin_tcandeleteescalations' => 'Может удалять Правила Обострения',
	'admin_canviewcfgroups' => 'Может смотреть Персональные Группы Полей',
	'admin_canviewcfields' => 'Может смотреть Персональные Поля',
	'admin_tmpcanviewgroups' => 'Может смотреть Группы Шаблонов',
	'admin_tmpcaninsertgroup' => 'Может добавлять Группы Шаблонов',
	'admin_tmpcanupdategroup' => 'Может обновлять Группы Шаблонов',
	'admin_tmpcandeletegroup' => 'Может удалять Группы Шаблонов',
	'admin_tmpcanviewtemplates' => 'Может смотреть Шаблоны',
	'admin_tmpcaninserttemplate' => 'Может добавлять Шаблоны',
	'admin_tmpcanrestoretemplates' => 'Может восстанавливать Шаблоны',
	'admin_tmpcanupdatetemplate' => 'Может обновлять Шаблоны',
	'admin_tmpcanrundiagnostics' => 'Может запускать диагностику Шаблонов',
	'admin_tmpcanrunimportexport' => 'Может запускать Импортирование/Экспортирование',
	'admin_tmpcanimportloginshare' => 'Может импортировать плагин LoginShare',
	'admin_tmpcanupdateloginshare' => 'Может обновлять настройки LoginShare',
	'admin_tmpcanviewloginshare' => 'Может смотреть плагины LoginShare',
	'admin_tmpcansearchtemplates' => 'Может искать Шаблоны',
	'admin_tmpcandeleteloginshare' => 'Может удалять плагины LoginShare',
	'admin_tcanviewworkflows' => 'Может смотреть Рабочие процессы',
	'admin_tcaninsertworkflow' => 'Может добавлять Рабочие процессы',
	'admin_tcanupdateworkflow' => 'Может обновлять Рабочие процессы',
	'admin_tcandeleteworkflows' => 'Может удалять Рабочие процессы',
	'admin_tcanviewstatus' => 'Может смотреть Статус',
	'admin_tcaninsertstatus' => 'Может добавлять Статус',
	'admin_tcanupdatestatus' => 'Может обновлять Статус',
	'admin_tcandeletestatus' => 'Может удалять Статус',
	'admin_tcanviewpriorities' => 'Может смотреть Приоритеты',
	'admin_tcaninsertpriority' => 'Может добавлять Приоритеты',
	'admin_tcanupdatepriority' => 'Может обновлять Приоритеты',
	'admin_tcandeletepriority' => 'Может удалять Приоритеты',
	'admin_tcanviewfiletypes' => 'Может смотреть Типы Файлов',
	'admin_tcaninsertfiletype' => 'Может добавлять Типы Файлов',
	'admin_tcanupdatefiletype' => 'Может обновлять Типы Файлов',
	'admin_tcandeletefiletypes' => 'Может удалять Типы Файлов',
	'admin_tcanviewlinks' => 'Может смотреть Связи',
	'admin_tcaninsertlink' => 'Может добавлять Связи',
	'admin_tcanupdatelink' => 'Может обновлять Связи',
	'admin_tcandeletelinks' => 'Может удалять Связи',
	'admin_tcanpurgeattachments' => 'Может очищать Вложения',
	'admin_tcanrunmaintenance' => 'может запускать Обслуживание Тикетов',
	'admin_mpcanviewloopblockages' => 'Может смотреть блокирования Цыклов',
	'admin_mpcandeleteloopblockages' => 'Может удалять блокирования Цыклов',
	'admin_mpcanviewlooprules' => 'Может смотреть правила Цыклов',
	'admin_mpcaninsertlooprule' => 'Может добавлять правила Цыклов',
	'admin_mpcanupdatelooprule' => 'Может обновлять правила Цыклов',
	'admin_mpcandeletelooprule' => 'Может удалять правила Цыклов',
	'staff_users' => 'Пользователи',
	'staff_usersorganizations' => 'Организации Пользователей',
	// ======= END v4 LOCALES =======

	/**
	* ###############################################
	* DEPARTMENT PERMISSIONS
	* ###############################################
	*/
	'd_ls_canhistory' => 'Может смотреть Записи Истории Чатов',
	'd_ls_canchat' => 'Может принимать/отклонять Чаты',
	'd_t_canreply' => 'Может отвечать на Тикеты',
	'd_t_canforward' => 'Может переадресовывать на Тикеты',
	'd_t_canfollowup' => 'Может создавать Слежения за Тикетами',
	'd_t_canbilling' => 'Может создавать Записи Оплаты',


	/**
	* ###############################################
	* TEAM PERMISSIONS
	* ###############################################
	*/
	// Troubleshooter Permissions
	'mod_troubleshooter' => 'Устранение неполадок',
	'tr_entab' => 'Может смотреть закладку Устранение неполадок',
	'tsmanagecategories' => 'Может управлять Категориями',
	'tsmanagesteps' => 'Может управлять Шагами',
	'tsinsertcategory' => 'Может добавлять Категорию',
	'tseditcategory' => 'Может редактировать Категорию',
	'tsdeletecategory' => 'Может удалять Категорию',
	'tsaddstep' => 'Может добавлять Новый Шаг Устранения неполадок',
	'tseditstep' => 'Может редактировать Существующий Шаг',
	'tsdeletestep' => 'Может удалять Шаг Устранения неполадок',
	'tsexport' => 'Может Экспортировать данные Устранения неполадок',
	'tsimport' => 'Может Импортировать данные Устранения неполадок',

	// Tickets
	'mod_tickets' => 'Тикеты',
	't_entab' => 'Может видеть Закладку Тикетов',
	'tmanage' => 'Может управлять Тикетами',
	'tdeleteview' => 'Может удалять Просмотры Тикетов',
	'teditview' => 'Может редактировать Просмотры Тикетов',
	'tnewticket' => 'Может создавать Новый Тикет',
	'tdeleteticket' => 'Может удалять Тикет',
	'tdeletepost' => 'Может удалять Сообщение Тикета',
	'teditpost' => 'Может редактировать Сообщение Тикета',
	'texport' => 'Может экспортировать как PDF/XML',
	'tforward' => 'Может перенаправлять Тикет',
	'tcrearule' => 'Может создавать Публичные Правила Оповещения',
	'tbilling' => 'Может добавлять оплачиваемые Записи',
	'tdelrecipients' => 'Может удалять получателей тикетов',
	'tmerge' => 'Может объединять Тикеты',
	'tdelarule' => 'Может удалять Публичные Правила Оповещения',
	'tupdarule' => 'Может редактировать Публичные Правила Оповещения',
	'tdellabel' => 'Может удалять Ярлык Тикета',
	'tcanviewall' => 'Может смотреть Все Тикеты <i>(Неприсвоенные, Присвоенные для него и Присвоенные другим)</i>',
	'tbanticket' => 'Может Банить Пользователей',
	'tbandelete' => 'Может Банить Пользователей и Удалять Тикеты',

	// Downloads
	'mod_downloads' => 'Загрузки',
	'dl_entab' => 'Может видеть закладку Загрузок',
	'dlcandelcat' => 'Может удалять Категорию',
	'dlcaneditcat' => 'Может редактировать Категорию',
	'dlcandelfile' => 'Может удалить Файл',
	'dlcaneditfile' => 'Может редактировать Файл',
	'dlcaninsertcat' => 'Может добавлять Категорию',
	'dlcaninsertfile' => 'Может добавлять Файл',

	// News
	'mod_news' => 'Новости',
	'nw_entab' => 'Может видет Закладку Новостей',

	// Knowledgebase
	'mod_knowledgebase' => 'База Знаний',
	'kb_entab' => 'Может видеть Закладку База Знаний',

	// Teamwork
	'mod_teamwork' => 'Групповая Работа',
	'tw_entab' => 'Может видеть Закладку Групповая Работа',

	// Live Chat
	'mod_livesupport' => 'Онлайн Консультант',
	'ls_entab' => 'Может видеть Закладку Онлайн Консультант',

	// Core
	'mod_core' => 'SWIFT Общее',
	'cu_entab' => 'Может видеть Закладку Пользователи',
);

?>