<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	// ======= BEGIN V4 LOCALES =======
	'insertholiday' => 'Добавить Праздник',
	'impex' => 'Импорт/Экспорт',
	'manageholidays' => 'Праздники',
	'desc_manageholidays' => '',
	'desc_insertholiday' => '',
	'holidaytitle' => 'Название Праздника',
	'desc_holidaytitle' => 'Введите название SLA Праздника',
	'holidaydate' => 'Дата Праздника',
	'desc_holidaydate' => 'Пожалуйста, укажите дату этого праздника',
	'tabslaplans' => 'SLA Планы',
	'flagicon' => 'Иконка Флага',
	'desc_flagicon' => 'Укажите Изображение иконки флага URL. По умолчанию  пакет иконки флага хранятся в темах / глобальные / каталог флагов. Вы можете использовать следующие переменные:<br><b>{$themepath}</b> - URL указатель для темы каталога <br> - Пример: {$themepath}us.gif',
	'slaplans' => 'Доступные SLA планы',
	'slaiscustom' => 'Связанно с персональными SLA планами',
	'desc_slaiscustom' => 'Укажите, будет ли этот праздник связан с персональным SLA планом',
	'customall' => 'вВе',
	'custom' => 'Персональный',
	'wineditslaholiday' => 'Изменить SLA Праздник: %s',
	'editholiday' => 'Изменить Праздник',
	'desc_editholiday' => '',
	'invalidslaholiday' => 'Неверный SLA Праздник. Пожалуйста, убедитесь, что SLA Праздник существует в базе данных.',
	'titleinsertslaholiday' => 'Добавлен SLA Праздник',
	'msginsertslaholiday' => 'Успешно выведен SLA Праздник "%s" в базу данных.',
	'titleupdateslaholiday' => 'Обновлено SLA Праздник',
	'msgupdateslaholiday' => 'Успешно обновление SLA Праздники "%s".',
	'titledelslaholidays' => 'Удален "%d" SLA Праздник(s)',
	'msgdelslaholidays' => 'Успешно удалены следующие SLA Праздники(s) из базы данных:',
	'slaimportexport' => 'Импорт/Экспорт',
	'desc_slaimportexport' => '',
	'tabexport' => 'Экспорт',
	'tabimport' => 'Импорт',
	'import' => 'Импорт',
	'export' => 'Экспорт',
	'exporttitle' => 'Название',
	'desc_exporttitle' => 'Введите название для этого SLA Праздника',
	'exportauthor' => 'Автор',
	'desc_exportauthor' => 'Введите автора этого SLA Праздника',
	'exportfilename' => 'Имя файла',
	'desc_exportfilename' => 'Укажите имя файла для этого SLA Праздника',
	'slaholidaypack' => 'SLA Праздник',
	'slaholidayfile' => 'SLA файл Праздника',
	'desc_slaholidayfile' => 'Загрузить xml файл SLA Праздников. '.SWIFT_PRODUCT.' будут импортированы все имеющиеся праздники в файле XML-пакет в базу данных.',
	'titleslaholidayimpex' => 'Импортировано SLA Пакет Праздника',
	'msgslaholidayimpex' => 'Успешно импортированы <b>"%d"</b> SLA Праздники(s) в базу данных.',
	'titleslaholidayimpexfailed' => 'SLA Holiday Pack Import Failed',
	'msgslaholidayimpexfailed' => 'Не удалось импортировать SLA Упаковку Праздника. Пожалуйста, убедитесь, что содержимое упаковки файлов содержит действительный XML '.SWIFT_PRODUCT.'.',
	'insertschedule' => 'Добавить Расписание',
	'desc_insertschedule' => '',
	'sladayopen24' => 'Открыто (24 часа)',
	'sladayclosed' => 'Закрыто',
	'sladayopencustom' => 'Окрито (Custom)',
	'titleinvalidhrange' => 'Неверный Диапазон часов',
	'msginvalidhrange' => 'Чтобы продолжить, Пожалуйста, исправьте диапазон часов,  что перечисленные ниже в SLA Расписании:',
	'manageschedules' => 'Управление расписанием',
	'desc_manageschedules' => '',
	'titleinsertslasched' => 'Добавлено SLA Расписание',
	'msginsertslasched' => 'Успешно выведено SLA Расписание "%s" в базу данных.',
	'titleupdateslasched' => 'Обновлено SLA Расписание',
	'msgupdateslasched' => 'Успешно обновлено SLA Расписание "%s".',
	'creationdate' => 'Дата создания',
	'invalidslaschedule' => 'Неверное SLA Расписание. Пожалуйста, убедитесь, что SLA Расписание существует в базе данных.',
	'editschedule' => 'Изменить расписание',
	'desc_editschedule' => '',
	'titleslaschedulenodel' => 'Не удается удалить SLA Расписание',
	'msgslaschedulenodel' => SWIFT_PRODUCT.' не в состоянии удалить следующие SLA расписания, как они связаны с некоторыми SLA планами. Пожалуйста, отсоедините их, чтобы удалить записи из базы данных.',
	'titledelslaschedules' => 'Удален "%d" SLA Расписание(s)',
	'msgdelslaschedules' => 'Успешно удален следующий SLA Расписание(s) из базы данных.',
	'slasettings' => 'SLA Настройки',
	'tabsettings' => 'Настройки',
	'sla' => 'SLA',
	'insertplan' => 'Добавить План',
	'desc_insertplan' => '',
	'tabholidays' => 'праздники',
	'plantitle' => 'План Тикета',
	'desc_plantitle' => 'Введите План Тикета.',
	'resolutionduehrs' => 'Ришение связи (Hours)',
	'desc_resolutionduehrs' => 'Введите число часов, после чего Тикет, как ожидается, будет помечен как решон.',
	'resolutionduehrs2' => 'Ришение (Часы)',
	'overduehrs' => 'Просроченный (Часы)',
	'desc_overduehrs' => 'Введите число часов, после которого Тикет отмечается как Запоздалый. Вы можете конкретизировать минуты как десятичные числа. Пример: 1.20',
	'planschedule' => 'SLA Расписание',
	'desc_planschedule' => 'Specify the Work Schedule that this SLA Plan is for. The Overdue time is calculated based on your Work Schedule automatically.',
	'smatchtype' => 'Тип соответствия',
	'matchtype' => 'Опции Критериев',
	'desc_matchtype' => 'Выберите метод группировки по критериям полей.',
	'smatchall' => 'Искать любое (AND)',
	'smatchany' => 'Искать любое (OR)',
	'isenabled' => 'Включен?',
	'desc_isenabled' => 'Переключить выполнение этого SLA  плана включения / отключения этой опции.',
	'sortorder' => 'Сортировка',
	'desc_sortorder' => 'Укажите порядок сортировки для этого Правила. Правила всегда обрабатываются в порядке возрастания.',
	'insertcriteria' => 'Добавить Критерию',
	'manageplans' => 'Планы',
	'schedules' => 'Расписание',
	'desc_manageplans' => '',
	'scheduletitle' => 'Название Расписания',
	'desc_scheduletitle' => '',
	'titlenocriteriaadded' => 'Нет Доступный Критериев',
	'msgnocriteriaadded' => 'Вам нужно добавить по крайней мере один критерий для того, чтобы вставить / редактировать SLA план.',
	'noscheduleavailable' => '-- Нет Доступного Расписания --',
	'titlenoslasched' => 'SLA Недоступное Расписание',
	'msgnoslasched' => 'Нет SLA добавленого Расписания (s) '. SWIFT_PRODUCT .'. Вам нужно добавить SLA расписание для того, чтобы вставить / обновить SLA план в системе.',
	'nocustomholidays' => 'Нет Доступных пользовательских Праздников. Вы можете переключаться это свойство при Управлении Праздниками &gt; Изменить',
	'editplan' => 'Изменить план',
	'desc_editplan' => '',
	'invalidslaplan' => 'Недействительный SLA План. Убедитесь, что план SLA существует в базе данных.',
	'titleslaplandel' => 'Удален "%d" SLA План(s)',
	'msgslaplandel' => 'Успешно Удален следеющий SLA План(s) из базы данных:',
	'titleslaplanenable' => 'Добавлен "%d" SLA План(s)',
	'msgslaplanenable' => 'Успешно добавлен следующий SLA план(s):',
	'titleslaplandisable' => 'Блокирован "%d" SLA План(s)',
	'msgslaplandisable' => 'Успешно блокирован следующий SLA план(s):',
	'linkedholidays' => 'Связанные праздники (Custom)',
	'titleslaplaninsert' => 'добавлен SLA План',
	'msgslaplaninsert' => 'Успешно добавлен SLA План "%s" в базу данных.',
	'titleslaplanupdate' => 'Обновлено SLA план',
	'msgslaplanupdate' => 'Успешно обновленный план SLA "%s".',
	'if' => 'If',
	'scheduledesc' => 'Расписание информации',

	// SLA Rules
	'srticketstatus' => 'Статус тикета',
	'desc_srticketstatus' => '',
	'srticketpriority' => 'Тикет Приоритета',
	'desc_srticketpriority' => '',
	'srdepartmentid' => 'Подраздиление',
	'desc_srdepartmentid' => '',
	'srownerstaffid' => 'Владелец Тикета',
	'desc_srownerstaffid' => '',
	'sremailqueueid' => 'Е-мейл Очереди',
	'srusergroupid' => 'Группа пользователей',
	'desc_srusergroupid' => '',
	'desc_sremailqueueid' => '',
	'notapplicable' => '-- NA --',
	'srfullname' => 'Полное имя',
	'desc_srfullname' => '',
	'sremail' => 'Е-мейл',
	'desc_sremail' => '',
	'srlastreplier' => 'Последний повтор',
	'desc_srlastreplier' => '',
	'srsubject' => 'Тема',
	'desc_srsubject' => '',
	'srcharset' => 'Набор символов',
	'desc_srcharset' => '',
	'srflagtype' => 'Тип Флага',
	'desc_srflagtype' => '',
	'srbayescategory' => 'Базовые категории',
	'desc_srbayescategory' => '',
	'purpleflag' => 'Пурпурный Флаг',
	'redflag' => 'Красный Флаг',
	'orangeflag' => 'Оранжевый Флаг',
	'yellowflag' => 'Жолтый Флаг',
	'blueflag' => 'Голубой Флаг',
	'greenflag' => 'Зеленый Флаг',
	'srcreator' => 'Создатель',
	'desc_srcreator' => '',
	'creatorstaff' => 'Работник',
	'creatorclient' => 'Пользователь',
	'srunassigned' => '-- Нераспределенные --',
	'srtemplategroup' => 'Группа шаблонов',
	'desc_srtemplategroup' => '',
	'srisresolved' => 'Разрешен?',
	'desc_srisresolved' => '',
	'srtickettype' => 'Тип Тикета',
	'desc_srtickettype' => '',
	'srwasreopened' => 'Был открыт?',
	'desc_srwasreopened' => '',
	'srtotalreplies' => 'Количество ответов',
	'desc_srtotalreplies' => '',


	'slajanuary' => 'Январь (01)',
	'slafebruary' => 'Февраль (02)',
	'slamarch' => 'Март (03)',
	'slaapril' => 'Апрель (04)',
	'slamay' => 'Май (05)',
	'slajune' => 'Июнь (06)',
	'slajuly' => 'Июля (07)',
	'slaaugust' => 'Август (08)',
	'slaseptember' => 'Сентябрь (09)',
	'slaoctober' => 'Октябрь (10)',
	'slanovember' => 'Ноябрь (11)',
	'sladecember' => 'Декабрь (12)',
	// ======= END V4 LOCALES =======
);
?>