<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	/*
	 * ###############################################
	 * BEGIN V4 LOCALES
	 * ###############################################
	 */
	'titlephlookup' => 'По данному номеру телефону пользователей не найдено %s',
	'msgphlookup' => SWIFT_PRODUCT . ' невозможно найти пользователя с номером телефона "%s".',
	'tabgeoip' => 'IP',
	'geoiptimezone' => 'Часовой Пояс',
	'geoipisp' => 'Провайдер',
	'geoiporganization' => 'Организация',
	'geoipnetspeed' => 'Скорость Интернета',
	'geoipcountry' => 'Страна',
	'geoipcountrydesc' => 'Страна',
	'geoipregion' => 'Регион',
	'geoipcity' => 'Город',
	'geoippostalcode' => 'Почтовый индекс',
	'geoiplatitude' => 'Широта',
	'geoiplongitude' => 'Долгота',
	'geoipmetrocode' => 'Метро',
	'geoipareacode' => 'Код Зоны',
	'tabcalls' => 'Звонки',
	'insertorganization' => 'Добавить Организацию',
	'editorganization' => 'Редактировать Организацию',
	'updateorg' => 'Обновить Организацию',
	'tabmassaction' => 'Массовые действия',
	'unochange' => '-- Без Изменений --',
	'merge' => 'Объединить',
	'mergeorganization' => 'Объединить Организации',
	'primaryorganization' => 'Первичная Организация',
	'infolastlogin' => 'Последний вход',
	'users' => 'Пользователи',
	'manageusers' => 'Управление Пользователяи',
	'userfullname' => 'Полное имя',
	'useremail' => 'Email',
	'userorganization' => 'Организация Пользователя',
	'desc_userorganization' => 'Введите Организацию Пользователя. Также Вы можете выбрать организацую, из списка.',
	'usergroup' => 'Группа Пользователя',
	'desc_usergroup' => 'Выберите группу, к которой относится пользователь. Все настройки даной группы будут применены для даного пользователя.',
	'insertuser' => 'Добавить Пользователя',
	'edituser' => 'Редактировать Пользователя',
	'infobuser' => 'Пользователь',
	'infobuserorganization' => 'Организация Пользователя',
	'infobusergroup' => 'Группа',
	'informationbox' => 'Информация',
	'userdesignation' => 'Должность',
	'desc_userdesignation' => 'Введите должность пользователя, которая будет отображатся в тикетах',
	'generaloptions' => 'Общие настройки',
	'useremails' => 'Email(ы) Пользователя',
	'desc_useremails' => 'Введите email адрес(а) Пользователя. Вы можете ввести несколько адресов, нажимая после каждого Ентер.',
	'userrole' => 'Роли пользователя',
	'desc_userrole' => 'Выберите Роли пользователя. При выборе Менеджер, юзер сможет смотреть другие тикеты, которые были созданы от имени организации, в которой он работает.',
	'userrolemanager' => 'Менеджер',
	'userroleuser' => 'Пользователь',
	'tabprofile' => 'Профиль',
	'taborganization' => 'Организация',
	'tabtickets' => 'Тикеты',
	'tabchats' => 'Чаты',
	'tabbilling' => 'Оплаты',
	'salutationmr' => 'г-н.',
	'salutationmiss' => 'г-жа.',
	'salutationmrs' => 'г-жа.',
	'salutationdr' => 'Д-р.',
	'isenabled' => 'Включено?',
	'desc_isenabled' => 'Выберите состояние пользователя. Если отключен, пользователь не сможет войти в центр поддержки.',
	'userexpiry' => 'Истекает',
	'desc_userexpiry' => 'Выберите время истечения аккаунта пользователя.',
	'userphone' => 'Номер телефона',
	'desc_userphone' => 'Введите номер телефона пользователя',
	'personalizeoptions' => 'Настроить',
	'userprofileimage' => 'Фотография',
	'desc_userprofileimage' => 'Загрузите фотографию Пользователя. Она будет отображена в тикетах и в чате.',
	'usertimezone' => 'Часовой Пояс',
	'desc_usertimezone' => 'Выберите Часовой Пояс пользователя.',
	'userenabledst' => 'Включить автопереход на летнее время',
	'desc_userenabledst' => 'Хотите ли Вы включить автопереход на летнее время.',
	'defaultlanguage' => '-- Язык по умолчанию --',
	'userlanguage' => 'Язык',
	'desc_userlanguage' => 'Выберите Язык по умолчанию для пользователя.',
	'usercustomsla' => 'Свои опции SLA плана',
	'defaultslaplan' => '-- Стандартный SLA план --',
	'userslaplan' => 'SLA план',
	'desc_userslaplan' => 'Выберите SLA план для пользователя.',
	'userslaexpiry' => 'SLA план истекает',
	'desc_userslaexpiry' => 'Выберите период истечения SLA плана.',
	'edituser' => 'Редактировать Пользователя',
	'edituserext' => 'Пользователь: %s',
	'titleemailexists' => 'Email Пользователя существует',
	'msgemailexists' => '"%s" email уже используется для пользователя с номером id "%d". Выберите другой адрес.',
	'titleuserinsert' => 'Добавлен Пользователь "%s"',
	'msguserinsert' => SWIFT_PRODUCT . ' успешно добавлен пользователь "%s", больше деталей:',
	'titleuserupdate' => 'Обновлен Пользователь "%s"',
	'msguserupdate' => SWIFT_PRODUCT . ' успешно обновлен пользователь "%s", больше деталей:',
	'titleinvalidfileext' => 'Неправильный формат изображения',
	'msginvalidfileext' => 'Формат изображение неправльный. Разрешенные форматы: gif, jpeg, jpg, png',
	'titledisableuser' => 'Отключен(ы) Пользователь(и) "%d"',
	'msgdisableuser' => 'Успешно отключен(ы) следующий(е) пользователь(и):<br />%s',
	'titleenableuser' => 'Включен(ы) Пользователь(и) "%d"',
	'msgenableuser' => 'Успешно включен(ы) следующий(е) пользователь(и):<br />%s',
	'titledeleteduser' => 'Удален(ы) пользователь(и) "%d"',
	'msgdeleteduser' => SWIFT_PRODUCT . ' Успешно удален(ы) следующий(е) пользователь(и):',
	'addnotes' => 'Заметки',
	'notetitle' => '%s в %s',
	'addnote' => 'Добавить Заметку',
	'tabaddnote' => 'Добавить Заметку',
	'usernotedelconfirm' => 'Вы уверены что хотите удалить Заметку Пользователя?',
	'editnote' => 'Редактировать Заметку',
	'tabeditnote' => 'Редактировать Заметку',
	'noteeditedtitle' => ' <i>(Отредактировал %s в %s)</i>',
	'manageorganizations' => 'Управление Организациями',
	'userorganizationshared' => 'Коллективный',
	'userorganizationrestricted' => 'Запрещенный',
	'organizationname' => 'Название Организации',
	'desc_organizationname' => 'Введите Название Организации.',
	'organizationtype' => 'Тип',
	'organizationtype2' => 'Тип Организации',
	'desc_organizationtype' => 'Выберите тип организации.',
	'titledeleteduserorganization' => 'Удалено организацию(и) "%d"',
	'msgdeleteduserorganization' => SWIFT_PRODUCT . ' успешно удалены следующие организации:',
	'userorganizationemails' => 'Фильтр Email адрессов Организаций',
	'desc_userorganizationemails' => 'Введите домены, которые принадлежат организации. ' . SWIFT_PRODUCT . ' автоматически отнесет пользователей, адреса которых находятся на даном домене к этой организации. Например: kayako.com google.com',
	'contactdetails' => 'Контактные Данные',
	'userorganizationslaplan' => 'SLA план',
	'desc_userorganizationslaplan' => 'Выберите SLA план для этой организации.',
	'userorganizationslaexpiry' => 'SLA план заканчивается',
	'desc_userorganizationslaexpiry' => 'Выберите когда SLA план заканчивается.',
	'organizationcity' => 'Город',
	'desc_organizationcity' => '',
	'organizationstate' => 'Регион',
	'desc_organizationstate' => '',
	'organizationcountry' => 'Страна',
	'desc_organizationcountry' => '',
	'organizationpostalcode' => 'Почтовый индекс',
	'desc_organizationpostalcode' => '',
	'organizationphone' => 'Телефон',
	'desc_organizationphone' => '',
	'organizationfax' => 'Факс',
	'desc_organizationfax' => '',
	'organizationwebsite' => 'Сайт',
	'desc_organizationwebsite' => '',
	'organizationaddress' => 'Адресс',
	'desc_organizationaddress' => '',
	'titleemailexistsorg' => 'Email Организации уже используется',
	'msgemailexistsorg' => '"%s" email организации уже используется организацией под id "%d". Выберите другой адресс.',
	'editorganization' => 'Редактировать Организацию',
	'editorganizationext' => 'Организация: %s',
	'titleorganizationinsert' => 'Добавлена Организация "%s"',
	'msgorganizationinsert' => SWIFT_PRODUCT . ' успешно добавлена организация "%s". Больше деталей:',
	'titleorganizationupdate' => 'Обновлена Организация "%s"',
	'msgorganizationupdate' => SWIFT_PRODUCT . ' успешно обновлена организация "%s". Больше деталей:',
	'titleorgnameexists' => 'Дублировать Название Организации',
	'msgorgnameexists' => SWIFT_PRODUCT . ' обнаружил организацию с таким же названием. Введите другое название для продолжения.',
	'tabusers' => 'Пользователи',
	'search' => 'Поиск',
	'tabsearch' => 'Поиск',
	'matchtype' => 'Критерии Поиска',
	'desc_matchtype' => 'Выберите метод групировки критерий поиска.',
	'smatchall' => 'Искать все (и)',
	'smatchany' => 'Искать любое (или)',
	'insertcriteria' => 'Добавить Критерий',
	'resetpassword' => 'Сбросить Пароль',
	'changepassword' => 'Изменить Пароль',
	'userpassword' => 'Пароль',
	'userpasswordagain' => 'Пароль (еще раз)',
	'generateandemail' => 'Генерировать и Email',
	'titlepwnomatch' => 'Неправильный Пароль',
	'msgpwnomatch' => 'Пароли не совпадают.',
	'titlepwupdated' => 'Пароль пользователя обновлен',
	'msgpwupdated' => SWIFT_PRODUCT . ' успешно обновлен пароль для пользователя "%s".',
	'titlepwgenerated' => 'Пароль Сгенерирован и отправлен на Email',
	'msgpwgenerated' => SWIFT_PRODUCT . ' згенерировал пароль для пользователя "%s" и отправил на e-mail.',

	/**
	 * ---------------------------------------------
	 * SEARCH CRITERIA
	 * ---------------------------------------------
	 */
	'usfullname' => 'Полное Имя',
	'usemail' => 'Email',
	'usdesignation' => 'Обозначение',
	'usphone' => 'Телефон',
	'ussalutation' => 'Приветсвие',
	'ususergroup' => 'Группа Пользователя',
	'ususerrole' => 'Роль Пользователя',
	'usorganization' => 'Организация',
	'usdateregistered' => 'Дата регистрации',
	'usdateregisteredrange' => 'Дата регистрации <дипазон>',
	'usdatelastupdate' => 'Дата последнего обновления',
	'usdatelastupdaterange' => 'Дата последнего обновления <дипазон>',
	'usdatelastvisit' => 'Дата последнего визита',
	'usdatelastvisitrange' => 'Дата последнего визита <дипазон>',
	'usisenabled' => 'Включен?',
	'usslaplan' => 'SLA план',
	'ususerexpiry' => 'Пользователь истекает',
	'usslaexpiry' => 'SLA истекает',
	'notapplicable' => '-- NA --',
	'lookup' => 'Просмотр',
	'usergroups' => 'Группы Пользователя',
	'titlevalidationpen' => 'Email адресс не подтвержден',
	'msgvalidatationpen' => 'Пользователь не подтвердил свой email адресс, нажмите "Подтвердить" для подтверждения вручную.',
	'markasverified' => 'Подтвердить',
	'titlevalidationsuccess' => 'Статус пользователя обновлен',
	'msgvalidationsuccess' => SWIFT_PRODUCT . ' отметил пользователя "%s" как подтвержденный. Пользователь теперь может войти в Центр поддержки.',



	/*
	 * ###############################################
	 * END V4 LOCALES
	 * ###############################################
	 */

	// ======= MANAGE USERS =======
	'userlist' => 'Список Пользователей',
	'usrfullnameandemail' => 'Полное имя и Email адресс',
	'desc_usrfullname' => 'Введите полное имя пользователя.',
	'desc_usremail' => 'Введите email адресс пользователя.',
	'usrgrouptitle' => 'Группа Пользователя',
	'usrlastvisit' => 'Последний Визит',
	'usrdate' => 'Дата добавления',
	'userdelconfirm' => 'Пользователь успешно удален',
	'userdelconfirmmsg' => 'Вы уверены что хотите удалить выбраного пользователя? Действие необратимое!',
	'usruserid' => 'ID Пользователя',
	'loginshare' => 'LoginShare',
	'usergroups2' => 'Группы Пользователя',
	'userlanguage' => 'Язык по-умолчанию',
	'desc_userlanguage' => 'Выберите язык по-умолчанию для пользователя.',
	'usertimezoneoffset' => 'Стандартный Часовой Пояс',
	'desc_usertimezoneoffset' => 'Выберите Часовой Пояс для пользователя.',
	'userenabled' => 'Пользователь Включен?',
	'desc_userenabled' => 'Если нет, пользователь не сможет войти в центр поддержки.',
	'wininsertuseremail' => 'Добавить Email',
	'loadingwindow' => 'Загрузка Окна..',
	'winedituseremail' => 'Редактировать Email',

	// ======= INSERT USER =======
	'insertuser' => 'Добавить Пользователя',
	'userdetails' => 'Детали Пользователя',
	'usrpassword' => 'Пароль',
	'desc_usrpassword' => 'Введите пароль для пользователя.',
	'usrpasswordconfirm' => 'Пароль (еще раз)',
	'desc_usrpasswordconfirm' => 'Введите пароль еще раз.',
	'usrformgroup' => 'Группа Пользователя',
	'desc_usrformgroup' => 'Выберите к какой группе относится пользователь.',
	'passworddontmatch' => 'ОШИБКА: Пароли не совпадают',
	'userinsertconfirm' => 'Пользователь "%s" успешно добавлен',
	'invalidemail' => 'ОШИБКА: введен неправльный email адресс',
	'uslaplan' => 'SLA план',
	'desc_uslaplan' => 'SLA план, выбранный здесь будет автоматичеки присвоен всем тикетам пользователя.',
	'uuser' => 'Пользователь',
	'umanager' => 'Менеджер',
	'usertype' => 'Тип Пользователя',
	'desc_usertype' => 'Выберите тип Пользователя',

	// ======= EDIT USER =======
	'updateuser' => 'Обновить Пользователя',
	'edituser' => 'Редактировать Пользователя',
	'invaliduser' => 'Неправильный Пользователь',
	'usrpasswordreset' => 'Сбросить Пароль',
	'useremaillist' => 'Список Email адресов',
	'uemaildelconfirmsg' => 'Вы уверены что хотите удалить этот email?',
	'insertnewuseremail' => 'Добавить Email',
	'cantdelprimaryemail' => 'ОШИБКА: невозможно удалить единственный email, присвоенный пользователю',
	'useremaildelconfirm' => 'Email пользователя успешно удален',
	'duplicateuseremail' => 'ОШИБКА: невозможно добавить email адресс; он уже используется другим пользователем',
	'useremailinsertconfirm' => 'Email адресс "%s" успешно добавлен',
	'userupdateconfirm' => 'Пользователь "%s" успешно обновлен',
	'invaliduseremail' => 'Неправильный email адресс',
	'useroptions' => 'Опции Пользователя',
	'deleteuser' => 'Удалить Пользователя',
	'createticket' => 'Создать Тикет',
	'tusearchticket' => 'Поиск Тикетов',
	'byuser' => 'По Пользователю',
	'byusergroup' => 'По группе пользователя',
	'validated' => 'Подтвержденный',
	'validationpending' => 'Ожидает Подтверждения',
	'markas' => 'Отметить Как',
	'valconfirm' => 'Успешно обновлен статус подтверждения "%s"',
	'markasvalidated' => 'Отметить как Подтвержденный',
	'markasvalidationpending' => 'Отметить как Ожидает Подтверждения',
	'resendverimail' => 'Отправить еще раз подтверждение на Email',
	'veriemailconfirm' => 'Письмо подтверждения отправлено на "%s"',
	'uregemailconfirm' => 'Письмо регистрации отправлено на "%s"',
	'resendregemail' => 'Отправить письмо регистрации на Email',

	// ======= EDIT USER EMAIL =======
	'edituseremail' => 'Редактировать Email адресс Пользователя',
	'useremailupdateconfirm' => 'Email адресс пользователя "%s" успешно обновлен',

	// ======= AJAX =======
	'tabnotes' => 'Заметки',
	'tabbilling' => 'Оплата',
	'tabticketreports' => 'Отчеты Тикетов',
	'tabchatreports' => 'Отчеты Чатов',
	'tabedit' => 'Редактировать',
	'loading' => 'Загрузка...',
);

?>