<?php
/**
 * =======================================
 * ###################################
 * SWIFT Framework
 *
 * @package	SWIFT
 * @author	Kayako Infotech Ltd.
 * @copyright	Copyright (c) 2001-2009, Kayako Infotech Ltd.
 * @license	http://www.kayako.com/license
 * @link		http://www.kayako.com
 * @filesource
 * ###################################
 * =======================================
 */

$__LANG = array (
	/*
	 * ###############################################
	 * BEGIN V4 LOCALES
	 * ###############################################
	 */
	'tf_staff.staffid' => 'ID Работника',
	'tf_staff.fullname' => 'Полное имя Работника',
	'tf_staff.designation' => 'Должность Работника',
	'tf_staff.staffgroupid' => 'ID Команды Работников',
	'tf_staff.email' => 'Email Работника',
	'tf_staff.lastactivity' => 'Последняя активность Работника',
	'tf_staff.isenabled' => 'Работник Включен',
	'tf_staff.passwordupdatetimeline' => 'Время обновления Пароля Работника',
	'tf_staff.timezonephp' => 'Часовой пояс Работника',
	'tf_staffgroup.staffgroupid' => 'ID Команды Работника',
	'tf_staffgroup.title' => 'Название Команды Работника',
	'tf_staffgroup.isadmin' => 'Является ли Команда Работника Администрацией',
	'tf_departments.slascheduleid' => 'ID SLA расписания Подразделения',
	'tf_departments.departmenttype' => 'Тип Подразделения',
	'tf_departments.parentdepartmentid' => 'ID Корневого Подразделения',
	'tf_departments.departmentmodule' => 'Модуль Подразделения',

	'tf_departments.title' => 'Название Подразделения',
	'tf_users.userid' => 'ID пользователя',
	'tf_users.usergroupid' => 'ID группы Пользователя',
	'tf_users.userorganizationid' => 'ID организации Пользователя',
	'tf_users.userrole' => 'Роли Пользователя',
	'tf_users.userdesignation' => 'Назначение Пользователя',
	'tf_users.fullname' => 'Полное имя пользователя',
	'tf_users.isenabled' => 'Пользователь включен',
	'tf_users.languageid' => 'ID языка пользователя',
	'tf_users.useremailcount' => 'Колличество e-mail-ов пользователя',
	'tf_users.slaplanid' => 'ID SLA плана пользователя',
	'tf_users.isvalidated' => 'Пользователь подтвержден',
	'tf_userorganizations.userorganizationid' => 'ID организации',
	'tf_userorganizations.organizationname' => 'Название организации',
	'tf_userorganizations.address' => 'Адресс организации',
	'tf_userorganizations.state' => 'Регион организации',
	'tf_userorganizations.postalcode' => 'Почтовый индекс организации',
	'tf_userorganizations.country' => 'Страна организации',
	'tf_userorganizations.phone' => 'Телефон организации',
	'tf_userorganizations.fax' => 'Факс организации',
	'tf_userorganizations.website' => 'Сайт организации',
	'tf_userorganizations.organizationtype' => 'Тип организации',
	'tf_userorganizations.languageid' => 'ID языка организации',
	'tf_userorganizations.slaplanid' => 'ID SLA плана организации',
	'tf_userorganizations.usergroupid' => 'ID группы пользователей организации',
	'tf_usergroups.usergroupid' => 'ID группы пользователей',
	'tf_usergroups.title' => 'Название группы пользователей',
	'tf_usergroups.ismaster' => 'Группа пользователей главная',
	'tf_useremails.email' => 'Email пользователя',
	'tf_tickets.ticketid' => 'ID тикета',
	'tf_tickets.ticketmaskid' => 'ID маски тикета',
	'tf_tickets.ownerstaffid' => 'ID присвоенного работника тикету',
	'tf_tickets.ticketstatusid' => 'ID статуса тикета',
	'tf_tickets.priorityid' => 'ID приоритета тикета',
	'tf_tickets.emailqueueid' => 'ID почтовой очереди тикета',
	'tf_tickets.fullname' => 'Полное имя автора тикета',
	'tf_tickets.email' => 'Email автора тикета',
	'tf_tickets.lastreplier' => 'Последний ответивший на тикет',
	'tf_tickets.replyto' => 'Тикет отвечен',
	'tf_tickets.subject' => 'Тема тикета',
	'tf_tickets.dateline' => 'Время тикета',
	'tf_tickets.lastactivity' => 'Последняя активность тикета',
	'tf_tickets.laststaffreplytime' => 'Последний ответ от работников на тикет',
	'tf_tickets.lastuserreplytime' => 'Последний ответ от пользователя на тикет',
	'tf_tickets.slaplanid' => 'ID SLA плана тикета',
	'tf_tickets.ticketslaplanid' => 'ID SLA плана тикета',
	'tf_tickets.duetime' => 'Время выполнения тикета',
	'tf_tickets.totalreplies' => 'Общее колличество ответов тикета',
	'tf_tickets.ipaddress' => 'IP адресс тикета',
	'tf_tickets.timeworked' => 'Время работы над тикетом',
	'tf_tickets.escalationruleid' => 'ID правила исключения тикета',
	'tf_tickets.autoclosetimeline' => 'Время авто-закрытия тикета',
	'tf_tickets.escalatedtime' => 'Время возрастания тикета',
	'tf_tickets.followupcount' => 'Колличетво работ над тикетом',
	'tf_tickets.isfirstcontactresolved' => 'Является ли первый ответ решением тикета',
	'tf_tickets.averageresponsetime' => 'Колличество потраченного времени на тикет',
	'tf_tickets.escalationlevelcount' => 'Колличество уровня возрастаний тикета',
	'tf_tickets.resolutiondateline' => 'Время решения тикета',
	'tf_tickets.wasreopened' => 'Тикет был заново открыт',
	'tf_tickets.reopenedateline' => 'Время нового открытия тикета',
	'tf_tickets.resolutionseconds' => 'Колличество секунд на решение тикета',
	'tf_tickets.resolutionduedateline' => 'Время до которого нудно решение тикета',
	'tf_tickets.isresolved' => 'Тикет решен',
	'tf_tickets.resolutionlevel' => 'Уровень решения тикета',
	'tf_tickets.departmentid' => 'ID Подразделения тикета',
	'tf_tickets.userid' => 'ID пользователя тикета',
	'tf_ticketstatus.ticketstatusid' => 'ID статуса тикета',
	'tf_ticketstatus.title' => 'Название статуса тикета',
	'tf_ticketstatus.markasresolved' => 'Статус Решен тикета',
	'tf_ticketstatus.departmentid' => 'ID подразделения статуса тикета',
	'tf_ticketstatus.type' => 'Тип статуса тикета',
	'tf_ticketpriorities.priorityid' => 'ID приоритета',
	'tf_ticketpriorities.title' => 'Название приоритета',
	'tf_chathits.chathitid' => 'ID просмотров чата',
	'tf_chathits.staffid' => 'ID просмотров чата Работниками',
	'tf_chathits.fullname' => 'Полное имя просмотров чата',
	'tf_chathits.email' => 'Email чата',
	'tf_chathits.isaccepted' => 'Чат принят',
	'tf_chathits.dateline' => 'Время Чата',
	'tf_chatskills.chatskillid' => 'ID навыков Чата',
	'tf_chatskills.title' => 'Название Навыков Чата',
	'tf_chatskilllinks.chatskilllinkid' => 'Chat Skill Link ID',
	'tf_chatskilllinks.chatskillid' => 'Chat Skill Link Skill ID',
	'tf_chatskilllinks.staffid' => 'Chat Skill Link Staff ID',
	'tf_slaplans.isenabled' => 'SLA план включен',
	'tf_slaplans.overduehours' => 'SLA план Колличество Просроченых часов',
	'tf_slaplans.resolutionhours' => 'SLA план потрачено Время на Решение',
	'tf_slaplans.resolutionduehours' => 'SLA Plan Resolution Due Hours',
	'tf_slaplans.title' => 'Название SLA плана',
	'tf_benchmarkresults.benchmarkresult' => 'Рейтинг',
	'tf_benchmarkresults.staffid' => 'Rating Result Staff ID',
	'tf_ticketposts.ticketpostid' => 'Ticket Post ID',
	'tf_tickettimetracks.creatorstaffname' => 'Имя создавшего Работника',
	'tf_tickettimetracks.timespent' => 'Потраченное время',
	'tf_tickettimetracks.timebillable' => 'Оплаченное Время',
	'tf_tickettimetracks.workerstaffname' => 'Worker Staff Name',
	'tf_tickettimetracks.dateline' => 'Billing Entry Date',

	'tab_staff' => 'Работники',
	'tab_staffgroup' => 'Команда Работников',
	'tab_departments' => 'Подразделения',
	'tab_users' => 'Пользователи',
	'tab_userorganizations' => 'Организации пользователей',
	'tab_usergroups' => 'Группы пользователей',
	'tab_tickets' => 'Тикеты',
	'tab_ticketstatus' => 'Статус тикета',
	'tab_ticketpriorities' => 'Приоритеты тикета',
	'tab_chathits' => 'Просмотры Чата',
	'tab_chatskills' => 'Навыки Чата',
	'tab_chatskilllinks' => 'Chat Skill Links',
	'tab_ticketposts' => 'Сообщения Тикетов',
	'tab_slaplans' => 'SLA планы',
	'tab_useremails' => 'Email-ы пользователей',
	'tab_tickettimetracks' => 'Billing',
);
?>